DROP TABLE IF EXISTS relay_server.characters;

CREATE TABLE relay_server.characters
(
    guid                 UUID PRIMARY KEY  DEFAULT gen_random_uuid(), -- Global Unique Identifier
    account              UUID     NOT NULL,                           -- Account Identifier
    name                 VARCHAR(12) COLLATE "C" UNIQUE,              -- бинарное сравнение как utf8mb4_bin
    race                 SMALLINT NOT NULL DEFAULT 0,
    class                SMALLINT NOT NULL DEFAULT 0,
    gender               SMALLINT NOT NULL DEFAULT 0,
    level                SMALLINT NOT NULL DEFAULT 0,
    xp                   INTEGER  NOT NULL DEFAULT 0,
    money                INTEGER  NOT NULL DEFAULT 0,
    skin                 SMALLINT NOT NULL DEFAULT 0,
    face                 SMALLINT NOT NULL DEFAULT 0,
    hairStyle            SMALLINT NOT NULL DEFAULT 0,
    hairColor            SMALLINT NOT NULL DEFAULT 0,
    facialStyle          SMALLINT NOT NULL DEFAULT 0,
    bankSlots            SMALLINT NOT NULL DEFAULT 0,
    restState            SMALLINT NOT NULL DEFAULT 0,
    playerFlags          INTEGER  NOT NULL DEFAULT 0,
    position_x           REAL     NOT NULL DEFAULT 0,
    position_y           REAL     NOT NULL DEFAULT 0,
    position_z           REAL     NOT NULL DEFAULT 0,
    map                  SMALLINT NOT NULL DEFAULT 0,                 -- Map Identifier
    instance_id          INTEGER  NOT NULL DEFAULT 0,
    instance_mode_mask   SMALLINT NOT NULL DEFAULT 0,
    orientation          REAL     NOT NULL DEFAULT 0,
    taximask             TEXT     NOT NULL,
    online               SMALLINT NOT NULL DEFAULT 0,
    cinematic            SMALLINT NOT NULL DEFAULT 0,
    totaltime            INTEGER  NOT NULL DEFAULT 0,
    leveltime            INTEGER  NOT NULL DEFAULT 0,
    logout_time          INTEGER  NOT NULL DEFAULT 0,
    is_logout_resting    SMALLINT NOT NULL DEFAULT 0,
    rest_bonus           REAL     NOT NULL DEFAULT 0,
    resettalents_cost    INTEGER  NOT NULL DEFAULT 0,
    resettalents_time    INTEGER  NOT NULL DEFAULT 0,
    trans_x              REAL     NOT NULL DEFAULT 0,
    trans_y              REAL     NOT NULL DEFAULT 0,
    trans_z              REAL     NOT NULL DEFAULT 0,
    trans_o              REAL     NOT NULL DEFAULT 0,
    transguid            INTEGER  NOT NULL DEFAULT 0,
    extra_flags          SMALLINT NOT NULL DEFAULT 0,
    stable_slots         SMALLINT NOT NULL DEFAULT 0,
    at_login             SMALLINT NOT NULL DEFAULT 0,
    zone                 SMALLINT NOT NULL DEFAULT 0,
    death_expire_time    INTEGER  NOT NULL DEFAULT 0,
    taxi_path            TEXT,
    arenaPoints          INTEGER  NOT NULL DEFAULT 0,
    totalHonorPoints     INTEGER  NOT NULL DEFAULT 0,
    todayHonorPoints     INTEGER  NOT NULL DEFAULT 0,
    yesterdayHonorPoints INTEGER  NOT NULL DEFAULT 0,
    totalKills           INTEGER  NOT NULL DEFAULT 0,
    todayKills           SMALLINT NOT NULL DEFAULT 0,
    yesterdayKills       SMALLINT NOT NULL DEFAULT 0,
    chosenTitle          INTEGER  NOT NULL DEFAULT 0,
    knownCurrencies      BIGINT   NOT NULL DEFAULT 0,
    watchedFaction       INTEGER  NOT NULL DEFAULT 0,
    drunk                SMALLINT NOT NULL DEFAULT 0,
    health               INTEGER  NOT NULL DEFAULT 0,
    power1               INTEGER  NOT NULL DEFAULT 0,
    power2               INTEGER  NOT NULL DEFAULT 0,
    power3               INTEGER  NOT NULL DEFAULT 0,
    power4               INTEGER  NOT NULL DEFAULT 0,
    power5               INTEGER  NOT NULL DEFAULT 0,
    power6               INTEGER  NOT NULL DEFAULT 0,
    power7               INTEGER  NOT NULL DEFAULT 0,
    latency              INTEGER  NOT NULL DEFAULT 0,
    talentGroupsCount    SMALLINT NOT NULL DEFAULT 1,
    activeTalentGroup    SMALLINT NOT NULL DEFAULT 0,
    exploredZones        TEXT,
    equipmentCache       TEXT,
    ammoId               INTEGER  NOT NULL DEFAULT 0,
    knownTitles          TEXT,
    actionBars           SMALLINT NOT NULL DEFAULT 0,
    grantableLevels      SMALLINT NOT NULL DEFAULT 0,
    deleteInfos_Account  UUID,
    deleteInfos_Name     VARCHAR(12),
    deleteDate           INTEGER
);

-- Индексы
CREATE INDEX idx_account ON relay_server.characters (account);
CREATE INDEX idx_online ON relay_server.characters (online);