#pragma once

#include <pqxx/pqxx>
#include <cstdint>
#include <optional>
#include <string>
#include "QueryResults.hpp"

struct DbcSpell {
    uint32_t id;
    uint32_t category;
    uint32_t dispelType;
    uint32_t mechanic;
    uint32_t attributes;
    uint32_t attributesEx;
    uint32_t attributesExB;
    uint32_t attributesExC;
    uint32_t attributesExD;
    uint32_t attributesExE;
    uint32_t attributesExF;
    uint32_t attributesExG;
    uint32_t shapeshiftMask1;
    uint32_t shapeshiftMask2;
    uint32_t shapeshiftExclude1;
    uint32_t shapeshiftExclude2;
    uint32_t targets;
    uint32_t targetCreatureType;
    uint32_t requiresSpellFocus;
    uint32_t facingCasterFlags;
    uint32_t casterAuraState;
    uint32_t targetAuraState;
    uint32_t excludeCasterAuraState;
    uint32_t excludeTargetAuraState;
    uint32_t casterAuraSpell;
    uint32_t targetAuraSpell;
    uint32_t excludeCasterAuraSpell;
    uint32_t excludeTargetAuraSpell;
    uint32_t castingTimeIndex;
    uint32_t recoveryTime;
    uint32_t categoryRecoveryTime;
    uint32_t interruptFlags;
    uint32_t auraInterruptFlags;
    uint32_t channelInterruptFlags;
    uint32_t procTypeMask;
    uint32_t procChance;
    uint32_t procCharges;
    uint32_t maxLevel;
    uint32_t baseLevel;
    uint32_t spellLevel;
    uint32_t durationIndex;
    int32_t powerType;
    uint32_t manaCost;
    uint32_t manaCostPerLevel;
    uint32_t manaPerSecond;
    uint32_t manaPerSecondPerLevel;
    uint32_t rangeIndex;
    float speed;
    uint32_t modalNextSpell;
    uint32_t cumulativeAura;
    uint32_t totem1;
    uint32_t totem2;
    int32_t reagent1;
    int32_t reagent2;
    int32_t reagent3;
    int32_t reagent4;
    int32_t reagent5;
    int32_t reagent6;
    int32_t reagent7;
    int32_t reagent8;
    int32_t reagentCount1;
    int32_t reagentCount2;
    int32_t reagentCount3;
    int32_t reagentCount4;
    int32_t reagentCount5;
    int32_t reagentCount6;
    int32_t reagentCount7;
    int32_t reagentCount8;
    int32_t equippedItemClass;
    int32_t equippedItemSubclass;
    int32_t equippedItemInvTypes;
    uint32_t effect1;
    uint32_t effect2;
    uint32_t effect3;
    int32_t effectDieSides1;
    int32_t effectDieSides2;
    int32_t effectDieSides3;
    float effectRealPointsPerLevel1;
    float effectRealPointsPerLevel2;
    float effectRealPointsPerLevel3;
    int32_t effectBasePoints1;
    int32_t effectBasePoints2;
    int32_t effectBasePoints3;
    uint32_t effectMechanic1;
    uint32_t effectMechanic2;
    uint32_t effectMechanic3;
    uint32_t implicitTargetA1;
    uint32_t implicitTargetA2;
    uint32_t implicitTargetA3;
    uint32_t implicitTargetB1;
    uint32_t implicitTargetB2;
    uint32_t implicitTargetB3;
    uint32_t effectRadiusIndex1;
    uint32_t effectRadiusIndex2;
    uint32_t effectRadiusIndex3;
    uint32_t effectAura1;
    uint32_t effectAura2;
    uint32_t effectAura3;
    uint32_t effectAuraPeriod1;
    uint32_t effectAuraPeriod2;
    uint32_t effectAuraPeriod3;
    float effectAmplitude1;
    float effectAmplitude2;
    float effectAmplitude3;
    uint32_t effectChainTargets1;
    uint32_t effectChainTargets2;
    uint32_t effectChainTargets3;
    uint32_t effectItemType1;
    uint32_t effectItemType2;
    uint32_t effectItemType3;
    int32_t effectMiscValue1;
    int32_t effectMiscValue2;
    int32_t effectMiscValue3;
    int32_t effectMiscValueB1;
    int32_t effectMiscValueB2;
    int32_t effectMiscValueB3;
    uint32_t effectTriggerSpell1;
    uint32_t effectTriggerSpell2;
    uint32_t effectTriggerSpell3;
    float effectPointsPerCombo1;
    float effectPointsPerCombo2;
    float effectPointsPerCombo3;
    uint32_t effectSpellClassMaskA1;
    uint32_t effectSpellClassMaskA2;
    uint32_t effectSpellClassMaskA3;
    uint32_t effectSpellClassMaskB1;
    uint32_t effectSpellClassMaskB2;
    uint32_t effectSpellClassMaskB3;
    uint32_t effectSpellClassMaskC1;
    uint32_t effectSpellClassMaskC2;
    uint32_t effectSpellClassMaskC3;
    uint32_t spellVisualID1;
    uint32_t spellVisualID2;
    uint32_t spellIconID;
    uint32_t activeIconID;
    uint32_t spellPriority;
    std::optional<std::string> nameLangEnUS;
    std::optional<std::string> nameLangEnGB;
    std::optional<std::string> nameLangKoKR;
    std::optional<std::string> nameLangFrFR;
    std::optional<std::string> nameLangDeDE;
    std::optional<std::string> nameLangEnCN;
    std::optional<std::string> nameLangZhCN;
    std::optional<std::string> nameLangEnTW;
    std::optional<std::string> nameLangZhTW;
    std::optional<std::string> nameLangEsES;
    std::optional<std::string> nameLangEsMX;
    std::optional<std::string> nameLangRuRU;
    std::optional<std::string> nameLangPtPT;
    std::optional<std::string> nameLangPtBR;
    std::optional<std::string> nameLangItIT;
    std::optional<std::string> nameLangUnk;
    uint32_t nameLangMask;
    std::optional<std::string> nameSubtextLangEnUS;
    std::optional<std::string> nameSubtextLangEnGB;
    std::optional<std::string> nameSubtextLangKoKR;
    std::optional<std::string> nameSubtextLangFrFR;
    std::optional<std::string> nameSubtextLangDeDE;
    std::optional<std::string> nameSubtextLangEnCN;
    std::optional<std::string> nameSubtextLangZhCN;
    std::optional<std::string> nameSubtextLangEnTW;
    std::optional<std::string> nameSubtextLangZhTW;
    std::optional<std::string> nameSubtextLangEsES;
    std::optional<std::string> nameSubtextLangEsMX;
    std::optional<std::string> nameSubtextLangRuRU;
    std::optional<std::string> nameSubtextLangPtPT;
    std::optional<std::string> nameSubtextLangPtBR;
    std::optional<std::string> nameSubtextLangItIT;
    std::optional<std::string> nameSubtextLangUnk;
    uint32_t nameSubtextLangMask;
    std::optional<std::string> descriptionLangEnUS;
    std::optional<std::string> descriptionLangEnGB;
    std::optional<std::string> descriptionLangKoKR;
    std::optional<std::string> descriptionLangFrFR;
    std::optional<std::string> descriptionLangDeDE;
    std::optional<std::string> descriptionLangEnCN;
    std::optional<std::string> descriptionLangZhCN;
    std::optional<std::string> descriptionLangEnTW;
    std::optional<std::string> descriptionLangZhTW;
    std::optional<std::string> descriptionLangEsES;
    std::optional<std::string> descriptionLangEsMX;
    std::optional<std::string> descriptionLangRuRU;
    std::optional<std::string> descriptionLangPtPT;
    std::optional<std::string> descriptionLangPtBR;
    std::optional<std::string> descriptionLangItIT;
    std::optional<std::string> descriptionLangUnk;
    uint32_t descriptionLangMask;
    std::optional<std::string> auraDescriptionLangEnUS;
    std::optional<std::string> auraDescriptionLangEnGB;
    std::optional<std::string> auraDescriptionLangKoKR;
    std::optional<std::string> auraDescriptionLangFrFR;
    std::optional<std::string> auraDescriptionLangDeDE;
    std::optional<std::string> auraDescriptionLangEnCN;
    std::optional<std::string> auraDescriptionLangZhCN;
    std::optional<std::string> auraDescriptionLangEnTW;
    std::optional<std::string> auraDescriptionLangZhTW;
    std::optional<std::string> auraDescriptionLangEsES;
    std::optional<std::string> auraDescriptionLangEsMX;
    std::optional<std::string> auraDescriptionLangRuRU;
    std::optional<std::string> auraDescriptionLangPtPT;
    std::optional<std::string> auraDescriptionLangPtBR;
    std::optional<std::string> auraDescriptionLangItIT;
    std::optional<std::string> auraDescriptionLangUnk;
    uint32_t auraDescriptionLangMask;
    uint32_t manaCostPct;
    uint32_t startRecoveryCategory;
    uint32_t startRecoveryTime;
    uint32_t maxTargetLevel;
    uint32_t spellClassSet;
    uint32_t spellClassMask1;
    uint32_t spellClassMask2;
    uint32_t spellClassMask3;
    uint32_t maxTargets;
    uint32_t defenseType;
    uint32_t preventionType;
    uint32_t stanceBarOrder;
    float effectChainAmplitude1;
    float effectChainAmplitude2;
    float effectChainAmplitude3;
    uint32_t minFactionId;
    uint32_t minReputation;
    uint32_t requiredAuraVision;
    uint32_t requiredTotemCategoryId1;
    uint32_t requiredTotemCategoryId2;
    int32_t requiredAreasId;
    uint32_t schoolMask;
    uint32_t runeCostId;
    uint32_t spellMissileId;
    int32_t powerDisplayId;
    float effectBonusCoefficient1;
    float effectBonusCoefficient2;
    float effectBonusCoefficient3;
    uint32_t spellDescriptionVariableId;
    uint32_t spellDifficultyId;
};

template<>
struct PgRowMapper<DbcSpell> {
    static DbcSpell map(const pqxx::row& r) {
        DbcSpell obj;
        obj.id = r["id"].as<uint32_t>();
        obj.category = r["category"].as<uint32_t>();
        obj.dispelType = r["dispeltype"].as<uint32_t>();
        obj.mechanic = r["mechanic"].as<uint32_t>();
        obj.attributes = r["attributes"].as<uint32_t>();
        obj.attributesEx = r["attributesex"].as<uint32_t>();
        obj.attributesExB = r["attributesexb"].as<uint32_t>();
        obj.attributesExC = r["attributesexc"].as<uint32_t>();
        obj.attributesExD = r["attributesexd"].as<uint32_t>();
        obj.attributesExE = r["attributesexe"].as<uint32_t>();
        obj.attributesExF = r["attributesexf"].as<uint32_t>();
        obj.attributesExG = r["attributesexg"].as<uint32_t>();
        obj.shapeshiftMask1 = r["shapeshiftmask_1"].as<uint32_t>();
        obj.shapeshiftMask2 = r["shapeshiftmask_2"].as<uint32_t>();
        obj.shapeshiftExclude1 = r["shapeshiftexclude_1"].as<uint32_t>();
        obj.shapeshiftExclude2 = r["shapeshiftexclude_2"].as<uint32_t>();
        obj.targets = r["targets"].as<uint32_t>();
        obj.targetCreatureType = r["targetcreaturetype"].as<uint32_t>();
        obj.requiresSpellFocus = r["requiresspellfocus"].as<uint32_t>();
        obj.facingCasterFlags = r["facingcasterflags"].as<uint32_t>();
        obj.casterAuraState = r["casteraurastate"].as<uint32_t>();
        obj.targetAuraState = r["targetaurastate"].as<uint32_t>();
        obj.excludeCasterAuraState = r["excludecasteraurastate"].as<uint32_t>();
        obj.excludeTargetAuraState = r["excludetargetaurastate"].as<uint32_t>();
        obj.casterAuraSpell = r["casterauraspell"].as<uint32_t>();
        obj.targetAuraSpell = r["targetauraspell"].as<uint32_t>();
        obj.excludeCasterAuraSpell = r["excludecasterauraspell"].as<uint32_t>();
        obj.excludeTargetAuraSpell = r["excludetargetauraspell"].as<uint32_t>();
        obj.castingTimeIndex = r["castingtimeindex"].as<uint32_t>();
        obj.recoveryTime = r["recoverytime"].as<uint32_t>();
        obj.categoryRecoveryTime = r["categoryrecoverytime"].as<uint32_t>();
        obj.interruptFlags = r["interruptflags"].as<uint32_t>();
        obj.auraInterruptFlags = r["aurainterruptflags"].as<uint32_t>();
        obj.channelInterruptFlags = r["channelinterruptflags"].as<uint32_t>();
        obj.procTypeMask = r["proctypemask"].as<uint32_t>();
        obj.procChance = r["procchance"].as<uint32_t>();
        obj.procCharges = r["proccharges"].as<uint32_t>();
        obj.maxLevel = r["maxlevel"].as<uint32_t>();
        obj.baseLevel = r["baselevel"].as<uint32_t>();
        obj.spellLevel = r["spelllevel"].as<uint32_t>();
        obj.durationIndex = r["durationindex"].as<uint32_t>();
        obj.powerType = r["powertype"].as<int32_t>();
        obj.manaCost = r["manacost"].as<uint32_t>();
        obj.manaCostPerLevel = r["manacostperlevel"].as<uint32_t>();
        obj.manaPerSecond = r["manapersecond"].as<uint32_t>();
        obj.manaPerSecondPerLevel = r["manapersecondperlevel"].as<uint32_t>();
        obj.rangeIndex = r["rangeindex"].as<uint32_t>();
        obj.speed = r["speed"].as<float>();
        obj.modalNextSpell = r["modalnextspell"].as<uint32_t>();
        obj.cumulativeAura = r["cumulativeaura"].as<uint32_t>();
        obj.totem1 = r["totem_1"].as<uint32_t>();
        obj.totem2 = r["totem_2"].as<uint32_t>();
        obj.reagent1 = r["reagent_1"].as<int32_t>();
        obj.reagent2 = r["reagent_2"].as<int32_t>();
        obj.reagent3 = r["reagent_3"].as<int32_t>();
        obj.reagent4 = r["reagent_4"].as<int32_t>();
        obj.reagent5 = r["reagent_5"].as<int32_t>();
        obj.reagent6 = r["reagent_6"].as<int32_t>();
        obj.reagent7 = r["reagent_7"].as<int32_t>();
        obj.reagent8 = r["reagent_8"].as<int32_t>();
        obj.reagentCount1 = r["reagentcount_1"].as<int32_t>();
        obj.reagentCount2 = r["reagentcount_2"].as<int32_t>();
        obj.reagentCount3 = r["reagentcount_3"].as<int32_t>();
        obj.reagentCount4 = r["reagentcount_4"].as<int32_t>();
        obj.reagentCount5 = r["reagentcount_5"].as<int32_t>();
        obj.reagentCount6 = r["reagentcount_6"].as<int32_t>();
        obj.reagentCount7 = r["reagentcount_7"].as<int32_t>();
        obj.reagentCount8 = r["reagentcount_8"].as<int32_t>();
        obj.equippedItemClass = r["equippeditemclass"].as<int32_t>();
        obj.equippedItemSubclass = r["equippeditemsubclass"].as<int32_t>();
        obj.equippedItemInvTypes = r["equippediteminvtypes"].as<int32_t>();
        obj.effect1 = r["effect_1"].as<uint32_t>();
        obj.effect2 = r["effect_2"].as<uint32_t>();
        obj.effect3 = r["effect_3"].as<uint32_t>();
        obj.effectDieSides1 = r["effectdiesides_1"].as<int32_t>();
        obj.effectDieSides2 = r["effectdiesides_2"].as<int32_t>();
        obj.effectDieSides3 = r["effectdiesides_3"].as<int32_t>();
        obj.effectRealPointsPerLevel1 = r["effectrealpointsperlevel_1"].as<float>();
        obj.effectRealPointsPerLevel2 = r["effectrealpointsperlevel_2"].as<float>();
        obj.effectRealPointsPerLevel3 = r["effectrealpointsperlevel_3"].as<float>();
        obj.effectBasePoints1 = r["effectbasepoints_1"].as<int32_t>();
        obj.effectBasePoints2 = r["effectbasepoints_2"].as<int32_t>();
        obj.effectBasePoints3 = r["effectbasepoints_3"].as<int32_t>();
        obj.effectMechanic1 = r["effectmechanic_1"].as<uint32_t>();
        obj.effectMechanic2 = r["effectmechanic_2"].as<uint32_t>();
        obj.effectMechanic3 = r["effectmechanic_3"].as<uint32_t>();
        obj.implicitTargetA1 = r["implicittargeta_1"].as<uint32_t>();
        obj.implicitTargetA2 = r["implicittargeta_2"].as<uint32_t>();
        obj.implicitTargetA3 = r["implicittargeta_3"].as<uint32_t>();
        obj.implicitTargetB1 = r["implicittargetb_1"].as<uint32_t>();
        obj.implicitTargetB2 = r["implicittargetb_2"].as<uint32_t>();
        obj.implicitTargetB3 = r["implicittargetb_3"].as<uint32_t>();
        obj.effectRadiusIndex1 = r["effectradiusindex_1"].as<uint32_t>();
        obj.effectRadiusIndex2 = r["effectradiusindex_2"].as<uint32_t>();
        obj.effectRadiusIndex3 = r["effectradiusindex_3"].as<uint32_t>();
        obj.effectAura1 = r["effectaura_1"].as<uint32_t>();
        obj.effectAura2 = r["effectaura_2"].as<uint32_t>();
        obj.effectAura3 = r["effectaura_3"].as<uint32_t>();
        obj.effectAuraPeriod1 = r["effectauraperiod_1"].as<uint32_t>();
        obj.effectAuraPeriod2 = r["effectauraperiod_2"].as<uint32_t>();
        obj.effectAuraPeriod3 = r["effectauraperiod_3"].as<uint32_t>();
        obj.effectAmplitude1 = r["effectamplitude_1"].as<float>();
        obj.effectAmplitude2 = r["effectamplitude_2"].as<float>();
        obj.effectAmplitude3 = r["effectamplitude_3"].as<float>();
        obj.effectChainTargets1 = r["effectchaintargets_1"].as<uint32_t>();
        obj.effectChainTargets2 = r["effectchaintargets_2"].as<uint32_t>();
        obj.effectChainTargets3 = r["effectchaintargets_3"].as<uint32_t>();
        obj.effectItemType1 = r["effectitemtype_1"].as<uint32_t>();
        obj.effectItemType2 = r["effectitemtype_2"].as<uint32_t>();
        obj.effectItemType3 = r["effectitemtype_3"].as<uint32_t>();
        obj.effectMiscValue1 = r["effectmiscvalue_1"].as<int32_t>();
        obj.effectMiscValue2 = r["effectmiscvalue_2"].as<int32_t>();
        obj.effectMiscValue3 = r["effectmiscvalue_3"].as<int32_t>();
        obj.effectMiscValueB1 = r["effectmiscvalueb_1"].as<int32_t>();
        obj.effectMiscValueB2 = r["effectmiscvalueb_2"].as<int32_t>();
        obj.effectMiscValueB3 = r["effectmiscvalueb_3"].as<int32_t>();
        obj.effectTriggerSpell1 = r["effecttriggerspell_1"].as<uint32_t>();
        obj.effectTriggerSpell2 = r["effecttriggerspell_2"].as<uint32_t>();
        obj.effectTriggerSpell3 = r["effecttriggerspell_3"].as<uint32_t>();
        obj.effectPointsPerCombo1 = r["effectpointspercombo_1"].as<float>();
        obj.effectPointsPerCombo2 = r["effectpointspercombo_2"].as<float>();
        obj.effectPointsPerCombo3 = r["effectpointspercombo_3"].as<float>();
        obj.effectSpellClassMaskA1 = r["effectspellclassmaska_1"].as<uint32_t>();
        obj.effectSpellClassMaskA2 = r["effectspellclassmaska_2"].as<uint32_t>();
        obj.effectSpellClassMaskA3 = r["effectspellclassmaska_3"].as<uint32_t>();
        obj.effectSpellClassMaskB1 = r["effectspellclassmaskb_1"].as<uint32_t>();
        obj.effectSpellClassMaskB2 = r["effectspellclassmaskb_2"].as<uint32_t>();
        obj.effectSpellClassMaskB3 = r["effectspellclassmaskb_3"].as<uint32_t>();
        obj.effectSpellClassMaskC1 = r["effectspellclassmaskc_1"].as<uint32_t>();
        obj.effectSpellClassMaskC2 = r["effectspellclassmaskc_2"].as<uint32_t>();
        obj.effectSpellClassMaskC3 = r["effectspellclassmaskc_3"].as<uint32_t>();
        obj.spellVisualID1 = r["spellvisualid_1"].as<uint32_t>();
        obj.spellVisualID2 = r["spellvisualid_2"].as<uint32_t>();
        obj.spellIconID = r["spelliconid"].as<uint32_t>();
        obj.activeIconID = r["activeiconid"].as<uint32_t>();
        obj.spellPriority = r["spellpriority"].as<uint32_t>();
        obj.nameLangEnUS = get_optional_string(r, "name_lang_enus");
        obj.nameLangEnGB = get_optional_string(r, "name_lang_engb");
        obj.nameLangKoKR = get_optional_string(r, "name_lang_kokr");
        obj.nameLangFrFR = get_optional_string(r, "name_lang_frfr");
        obj.nameLangDeDE = get_optional_string(r, "name_lang_dede");
        obj.nameLangEnCN = get_optional_string(r, "name_lang_encn");
        obj.nameLangZhCN = get_optional_string(r, "name_lang_zhcn");
        obj.nameLangEnTW = get_optional_string(r, "name_lang_entw");
        obj.nameLangZhTW = get_optional_string(r, "name_lang_zhtw");
        obj.nameLangEsES = get_optional_string(r, "name_lang_eses");
        obj.nameLangEsMX = get_optional_string(r, "name_lang_esmx");
        obj.nameLangRuRU = get_optional_string(r, "name_lang_ruru");
        obj.nameLangPtPT = get_optional_string(r, "name_lang_ptpt");
        obj.nameLangPtBR = get_optional_string(r, "name_lang_ptbr");
        obj.nameLangItIT = get_optional_string(r, "name_lang_itit");
        obj.nameLangUnk = get_optional_string(r, "name_lang_unk");
        obj.nameLangMask = r["name_lang_mask"].as<uint32_t>();
        obj.nameSubtextLangEnUS = get_optional_string(r, "namesubtext_lang_enus");
        obj.nameSubtextLangEnGB = get_optional_string(r, "namesubtext_lang_engb");
        obj.nameSubtextLangKoKR = get_optional_string(r, "namesubtext_lang_kokr");
        obj.nameSubtextLangFrFR = get_optional_string(r, "namesubtext_lang_frfr");
        obj.nameSubtextLangDeDE = get_optional_string(r, "namesubtext_lang_dede");
        obj.nameSubtextLangEnCN = get_optional_string(r, "namesubtext_lang_encn");
        obj.nameSubtextLangZhCN = get_optional_string(r, "namesubtext_lang_zhcn");
        obj.nameSubtextLangEnTW = get_optional_string(r, "namesubtext_lang_entw");
        obj.nameSubtextLangZhTW = get_optional_string(r, "namesubtext_lang_zhtw");
        obj.nameSubtextLangEsES = get_optional_string(r, "namesubtext_lang_eses");
        obj.nameSubtextLangEsMX = get_optional_string(r, "namesubtext_lang_esmx");
        obj.nameSubtextLangRuRU = get_optional_string(r, "namesubtext_lang_ruru");
        obj.nameSubtextLangPtPT = get_optional_string(r, "namesubtext_lang_ptpt");
        obj.nameSubtextLangPtBR = get_optional_string(r, "namesubtext_lang_ptbr");
        obj.nameSubtextLangItIT = get_optional_string(r, "namesubtext_lang_itit");
        obj.nameSubtextLangUnk = get_optional_string(r, "namesubtext_lang_unk");
        obj.nameSubtextLangMask = r["namesubtext_lang_mask"].as<uint32_t>();
        obj.descriptionLangEnUS = get_optional_string(r, "description_lang_enus");
        obj.descriptionLangEnGB = get_optional_string(r, "description_lang_engb");
        obj.descriptionLangKoKR = get_optional_string(r, "description_lang_kokr");
        obj.descriptionLangFrFR = get_optional_string(r, "description_lang_frfr");
        obj.descriptionLangDeDE = get_optional_string(r, "description_lang_dede");
        obj.descriptionLangEnCN = get_optional_string(r, "description_lang_encn");
        obj.descriptionLangZhCN = get_optional_string(r, "description_lang_zhcn");
        obj.descriptionLangEnTW = get_optional_string(r, "description_lang_entw");
        obj.descriptionLangZhTW = get_optional_string(r, "description_lang_zhtw");
        obj.descriptionLangEsES = get_optional_string(r, "description_lang_eses");
        obj.descriptionLangEsMX = get_optional_string(r, "description_lang_esmx");
        obj.descriptionLangRuRU = get_optional_string(r, "description_lang_ruru");
        obj.descriptionLangPtPT = get_optional_string(r, "description_lang_ptpt");
        obj.descriptionLangPtBR = get_optional_string(r, "description_lang_ptbr");
        obj.descriptionLangItIT = get_optional_string(r, "description_lang_itit");
        obj.descriptionLangUnk = get_optional_string(r, "description_lang_unk");
        obj.descriptionLangMask = r["description_lang_mask"].as<uint32_t>();
        obj.auraDescriptionLangEnUS = get_optional_string(r, "auradescription_lang_enus");
        obj.auraDescriptionLangEnGB = get_optional_string(r, "auradescription_lang_engb");
        obj.auraDescriptionLangKoKR = get_optional_string(r, "auradescription_lang_kokr");
        obj.auraDescriptionLangFrFR = get_optional_string(r, "auradescription_lang_frfr");
        obj.auraDescriptionLangDeDE = get_optional_string(r, "auradescription_lang_dede");
        obj.auraDescriptionLangEnCN = get_optional_string(r, "auradescription_lang_encn");
        obj.auraDescriptionLangZhCN = get_optional_string(r, "auradescription_lang_zhcn");
        obj.auraDescriptionLangEnTW = get_optional_string(r, "auradescription_lang_entw");
        obj.auraDescriptionLangZhTW = get_optional_string(r, "auradescription_lang_zhtw");
        obj.auraDescriptionLangEsES = get_optional_string(r, "auradescription_lang_eses");
        obj.auraDescriptionLangEsMX = get_optional_string(r, "auradescription_lang_esmx");
        obj.auraDescriptionLangRuRU = get_optional_string(r, "auradescription_lang_ruru");
        obj.auraDescriptionLangPtPT = get_optional_string(r, "auradescription_lang_ptpt");
        obj.auraDescriptionLangPtBR = get_optional_string(r, "auradescription_lang_ptbr");
        obj.auraDescriptionLangItIT = get_optional_string(r, "auradescription_lang_itit");
        obj.auraDescriptionLangUnk = get_optional_string(r, "auradescription_lang_unk");
        obj.auraDescriptionLangMask = r["auradescription_lang_mask"].as<uint32_t>();
        obj.manaCostPct = r["manacostpct"].as<uint32_t>();
        obj.startRecoveryCategory = r["startrecoverycategory"].as<uint32_t>();
        obj.startRecoveryTime = r["startrecoverytime"].as<uint32_t>();
        obj.maxTargetLevel = r["maxtargetlevel"].as<uint32_t>();
        obj.spellClassSet = r["spellclassset"].as<uint32_t>();
        obj.spellClassMask1 = r["spellclassmask_1"].as<uint32_t>();
        obj.spellClassMask2 = r["spellclassmask_2"].as<uint32_t>();
        obj.spellClassMask3 = r["spellclassmask_3"].as<uint32_t>();
        obj.maxTargets = r["maxtargets"].as<uint32_t>();
        obj.defenseType = r["defensetype"].as<uint32_t>();
        obj.preventionType = r["preventiontype"].as<uint32_t>();
        obj.stanceBarOrder = r["stancebarorder"].as<uint32_t>();
        obj.effectChainAmplitude1 = r["effectchainamplitude_1"].as<float>();
        obj.effectChainAmplitude2 = r["effectchainamplitude_2"].as<float>();
        obj.effectChainAmplitude3 = r["effectchainamplitude_3"].as<float>();
        obj.minFactionId = r["minfactionid"].as<uint32_t>();
        obj.minReputation = r["minreputation"].as<uint32_t>();
        obj.requiredAuraVision = r["requiredauravision"].as<uint32_t>();
        obj.requiredTotemCategoryId1 = r["requiredtotemcategoryid_1"].as<uint32_t>();
        obj.requiredTotemCategoryId2 = r["requiredtotemcategoryid_2"].as<uint32_t>();
        obj.requiredAreasId = r["requiredareasid"].as<int32_t>();
        obj.schoolMask = r["schoolmask"].as<uint32_t>();
        obj.runeCostId = r["runecostid"].as<uint32_t>();
        obj.spellMissileId = r["spellmissileid"].as<uint32_t>();
        obj.powerDisplayId = r["powerdisplayid"].as<int32_t>();
        obj.effectBonusCoefficient1 = r["effectbonuscoefficient_1"].as<float>();
        obj.effectBonusCoefficient2 = r["effectbonuscoefficient_2"].as<float>();
        obj.effectBonusCoefficient3 = r["effectbonuscoefficient_3"].as<float>();
        obj.spellDescriptionVariableId = r["spelldescriptionvariableid"].as<uint32_t>();
        obj.spellDifficultyId = r["spelldifficultyid"].as<uint32_t>();
        return obj;
    }
};