DROP TABLE IF EXISTS dbc.dbc_vehicle;

CREATE TABLE dbc.dbc_vehicle
(
    id                      INTEGER PRIMARY KEY DEFAULT 0,
    flags                   INTEGER NOT NULL    DEFAULT 0,
    turnspeed               REAL    NOT NULL    DEFAULT 0,
    pitchspeed              REAL    NOT NULL    DEFAULT 0,
    pitchmin                REAL    NOT NULL    DEFAULT 0,
    pitchmax                REAL    NOT NULL    DEFAULT 0,
    seatid_1                INTEGER NOT NULL    DEFAULT 0,
    seatid_2                INTEGER NOT NULL    DEFAULT 0,
    seatid_3                INTEGER NOT NULL    DEFAULT 0,
    seatid_4                INTEGER NOT NULL    DEFAULT 0,
    seatid_5                INTEGER NOT NULL    DEFAULT 0,
    seatid_6                INTEGER NOT NULL    DEFAULT 0,
    seatid_7                INTEGER NOT NULL    DEFAULT 0,
    seatid_8                INTEGER NOT NULL    DEFAULT 0,
    mouselookoffsetpitch    REAL    NOT NULL    DEFAULT 0,
    camerafadedistscalarmin REAL    NOT NULL    DEFAULT 0,
    camerafadedistscalarmax REAL    NOT NULL    DEFAULT 0,
    camerapitchoffset       REAL    NOT NULL    DEFAULT 0,
    facinglimitright        REAL    NOT NULL    DEFAULT 0,
    facinglimitleft         REAL    NOT NULL    DEFAULT 0,
    mssltrgtturnlingering   REAL    NOT NULL    DEFAULT 0,
    mssltrgtpitchlingering  REAL    NOT NULL    DEFAULT 0,
    mssltrgtmouselingering  REAL    NOT NULL    DEFAULT 0,
    mssltrgtendopacity      REAL    NOT NULL    DEFAULT 0,
    mssltrgtarcspeed        REAL    NOT NULL    DEFAULT 0,
    mssltrgtarcrepeat       REAL    NOT NULL    DEFAULT 0,
    mssltrgtarcwidth        REAL    NOT NULL    DEFAULT 0,
    mssltrgtimpactradius_1  REAL    NOT NULL    DEFAULT 0,
    mssltrgtimpactradius_2  REAL    NOT NULL    DEFAULT 0,
    mssltrgtarctexture      TEXT,
    mssltrgtimpacttexture   TEXT,
    mssltrgtimpactmodel_1   TEXT,
    mssltrgtimpactmodel_2   TEXT,
    camerayawoffset         REAL    NOT NULL    DEFAULT 0,
    uilocomotiontype        INTEGER NOT NULL    DEFAULT 0,
    mssltrgtimpacttexradius REAL    NOT NULL    DEFAULT 0,
    vehicleuiindicatorid    INTEGER NOT NULL    DEFAULT 0,
    powerdisplayid_1        INTEGER NOT NULL    DEFAULT 0,
    powerdisplayid_2        INTEGER NOT NULL    DEFAULT 0,
    powerdisplayid_3        INTEGER NOT NULL    DEFAULT 0
);
