DROP TABLE IF EXISTS dbc.dbc_achievement;

CREATE TABLE dbc.dbc_achievement
(
    ID                    integer NOT NULL DEFAULT 0,
    Faction               integer NOT NULL DEFAULT 0,
    Instance_Id           integer NOT NULL DEFAULT 0,
    Supercedes            integer NOT NULL DEFAULT 0,

    Title_Lang_enUS       text,
    Title_Lang_enGB       text,
    Title_Lang_koKR       text,
    Title_Lang_frFR       text,
    Title_Lang_deDE       text,
    Title_Lang_enCN       text,
    Title_Lang_zhCN       text,
    Title_Lang_enTW       text,
    Title_Lang_zhTW       text,
    Title_Lang_esES       text,
    Title_Lang_esMX       text,
    Title_Lang_ruRU       text,
    Title_Lang_ptPT       text,
    Title_Lang_ptBR       text,
    Title_Lang_itIT       text,
    Title_Lang_Unk        text,
    Title_Lang_Mask       bigint  NOT NULL DEFAULT 0,

    Description_Lang_enUS text,
    Description_Lang_enGB text,
    Description_Lang_koKR text,
    Description_Lang_frFR text,
    Description_Lang_deDE text,
    Description_Lang_enCN text,
    Description_Lang_zhCN text,
    Description_Lang_enTW text,
    Description_Lang_zhTW text,
    Description_Lang_esES text,
    Description_Lang_esMX text,
    Description_Lang_ruRU text,
    Description_Lang_ptPT text,
    Description_Lang_ptBR text,
    Description_Lang_itIT text,
    Description_Lang_Unk  text,
    Description_Lang_Mask bigint  NOT NULL DEFAULT 0,

    Category              integer NOT NULL DEFAULT 0,
    Points                integer NOT NULL DEFAULT 0,
    Ui_Order              integer NOT NULL DEFAULT 0,
    Flags                 integer NOT NULL DEFAULT 0,
    IconID                integer NOT NULL DEFAULT 0,

    Reward_Lang_enUS      text,
    Reward_Lang_enGB      text,
    Reward_Lang_koKR      text,
    Reward_Lang_frFR      text,
    Reward_Lang_deDE      text,
    Reward_Lang_enCN      text,
    Reward_Lang_zhCN      text,
    Reward_Lang_enTW      text,
    Reward_Lang_zhTW      text,
    Reward_Lang_esES      text,
    Reward_Lang_esMX      text,
    Reward_Lang_ruRU      text,
    Reward_Lang_ptPT      text,
    Reward_Lang_ptBR      text,
    Reward_Lang_itIT      text,
    Reward_Lang_Unk       text,
    Reward_Lang_Mask      bigint  NOT NULL DEFAULT 0,

    Minimum_Criteria      integer NOT NULL DEFAULT 0,
    Shares_Criteria       integer NOT NULL DEFAULT 0,

    CONSTRAINT pk_dbc_achievement PRIMARY KEY (ID)
);
