DROP TABLE IF EXISTS dbc.dbc_chrraces;

CREATE TABLE dbc.dbc_chrraces
(
    ID                        integer NOT NULL DEFAULT 0,
    Flags                     integer NOT NULL DEFAULT 0,
    FactionID                 integer NOT NULL DEFAULT 0,
    ExplorationSoundID        integer NOT NULL DEFAULT 0,
    MaleDisplayId             integer NOT NULL DEFAULT 0,
    FemaleDisplayId           integer NOT NULL DEFAULT 0,
    ClientPrefix              text,
    BaseLanguage              integer NOT NULL DEFAULT 0,
    CreatureType              integer NOT NULL DEFAULT 0,
    ResSicknessSpellID        integer NOT NULL DEFAULT 0,
    SplashSoundID             integer NOT NULL DEFAULT 0,
    ClientFilestring          text,
    CinematicSequenceID       integer NOT NULL DEFAULT 0,
    Alliance                  integer NOT NULL DEFAULT 0,
    Name_Lang_enUS            text,
    Name_Lang_enGB            text,
    Name_Lang_koKR            text,
    Name_Lang_frFR            text,
    Name_Lang_deDE            text,
    Name_Lang_enCN            text,
    Name_Lang_zhCN            text,
    Name_Lang_enTW            text,
    Name_Lang_zhTW            text,
    Name_Lang_esES            text,
    Name_Lang_esMX            text,
    Name_Lang_ruRU            text,
    Name_Lang_ptPT            text,
    Name_Lang_ptBR            text,
    Name_Lang_itIT            text,
    Name_Lang_Unk             text,
    Name_Lang_Mask            integer NOT NULL DEFAULT 0,
    Name_Female_Lang_enUS     text,
    Name_Female_Lang_enGB     text,
    Name_Female_Lang_koKR     text,
    Name_Female_Lang_frFR     text,
    Name_Female_Lang_deDE     text,
    Name_Female_Lang_enCN     text,
    Name_Female_Lang_zhCN     text,
    Name_Female_Lang_enTW     text,
    Name_Female_Lang_zhTW     text,
    Name_Female_Lang_esES     text,
    Name_Female_Lang_esMX     text,
    Name_Female_Lang_ruRU     text,
    Name_Female_Lang_ptPT     text,
    Name_Female_Lang_ptBR     text,
    Name_Female_Lang_itIT     text,
    Name_Female_Lang_Unk      text,
    Name_Female_Lang_Mask     integer NOT NULL DEFAULT 0,
    Name_Male_Lang_enUS       text,
    Name_Male_Lang_enGB       text,
    Name_Male_Lang_koKR       text,
    Name_Male_Lang_frFR       text,
    Name_Male_Lang_deDE       text,
    Name_Male_Lang_enCN       text,
    Name_Male_Lang_zhCN       text,
    Name_Male_Lang_enTW       text,
    Name_Male_Lang_zhTW       text,
    Name_Male_Lang_esES       text,
    Name_Male_Lang_esMX       text,
    Name_Male_Lang_ruRU       text,
    Name_Male_Lang_ptPT       text,
    Name_Male_Lang_ptBR       text,
    Name_Male_Lang_itIT       text,
    Name_Male_Lang_Unk        text,
    Name_Male_Lang_Mask       integer NOT NULL DEFAULT 0,
    FacialHairCustomization_1 text,
    FacialHairCustomization_2 text,
    HairCustomization         text,
    Required_Expansion        integer NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

COMMENT ON TABLE dbc.dbc_chrraces IS 'ChrRaces.dbc';

INSERT INTO dbc.dbc_chrraces (
    ID, Flags, FactionID, ExplorationSoundID, MaleDisplayId, FemaleDisplayId,
    ClientPrefix, BaseLanguage, CreatureType, ResSicknessSpellID, SplashSoundID,
    ClientFilestring, CinematicSequenceID, Alliance,
    Name_Lang_enUS, Name_Lang_enGB, Name_Lang_koKR, Name_Lang_frFR, Name_Lang_deDE,
    Name_Lang_enCN, Name_Lang_zhCN, Name_Lang_enTW, Name_Lang_zhTW, Name_Lang_esES,
    Name_Lang_esMX, Name_Lang_ruRU, Name_Lang_ptPT, Name_Lang_ptBR, Name_Lang_itIT,
    Name_Lang_Unk, Name_Lang_Mask,
    Name_Female_Lang_enUS, Name_Female_Lang_enGB, Name_Female_Lang_koKR,
    Name_Female_Lang_frFR, Name_Female_Lang_deDE, Name_Female_Lang_enCN,
    Name_Female_Lang_zhCN, Name_Female_Lang_enTW, Name_Female_Lang_zhTW,
    Name_Female_Lang_esES, Name_Female_Lang_esMX, Name_Female_Lang_ruRU,
    Name_Female_Lang_ptPT, Name_Female_Lang_ptBR, Name_Female_Lang_itIT,
    Name_Female_Lang_Unk, Name_Female_Lang_Mask,
    Name_Male_Lang_enUS, Name_Male_Lang_enGB, Name_Male_Lang_koKR,
    Name_Male_Lang_frFR, Name_Male_Lang_deDE, Name_Male_Lang_enCN,
    Name_Male_Lang_zhCN, Name_Male_Lang_enTW, Name_Male_Lang_zhTW,
    Name_Male_Lang_esES, Name_Male_Lang_esMX, Name_Male_Lang_ruRU,
    Name_Male_Lang_ptPT, Name_Male_Lang_ptBR, Name_Male_Lang_itIT,
    Name_Male_Lang_Unk, Name_Male_Lang_Mask,
    FacialHairCustomization_1, FacialHairCustomization_2, HairCustomization,
    Required_Expansion
) VALUES
      (1,12,1,4140,49,50,'Hu',7,7,15007,1096,'Human',81,0,'Human','Human','인간','Humain','Mensch','人类','人类','人類','人類','Humano','Humano','Человек','','','','',16712191,'','','','Humaine','','','','','','Humana','Humana','','','','','',16712172,'','','','Humain','Mensch','','','','','Humano','Humano','Человек','','','','',16712172,'NORMAL','PIERCINGS','NORMAL',0),
      (2,12,2,4141,51,52,'Or',1,7,15007,1096,'Orc',21,1,'Orc','Orc','오크','Orc','Orc','兽人','兽人','獸人','獸人','Orco','Orco','Орк','','','','',16712191,'','','','Orque','','','','','','Orco','Orco','','','','','',16712172,'','','','Orc','Orc','','','','','Orco','Orco','Орк','','','','',16712172,'NORMAL','PIERCINGS','NORMAL',0),
      (3,12,3,4147,53,54,'Dw',7,7,15007,1090,'Dwarf',41,0,'Dwarf','Dwarf','드워프','Nain','Zwerg','矮人','矮人','矮人','矮人','Enano','Enano','Дворф','','','','',16712191,'','','','Naine','','','','','','Enana','Enana','','','','','',16712172,'','','','Nain','Zwerg','','','','','Enano','Enano','Дворф','','','','',16712172,'NORMAL','PIERCINGS','NORMAL',0),
      (4,4,4,4145,55,56,'Ni',7,7,15007,1096,'NightElf',61,0,'Night Elf','Night Elf','나이트 엘프','Elfe de la nuit','Nachtelf','暗夜精灵','暗夜精灵','夜精靈','夜精靈','Elfo de la noche','Elfo de la noche','Ночной эльф','','','','',16712191,'','','','Elfe de la nuit','Nachtelfe','','','','','Elfa de la noche','Elfa de la noche','Ночная эльфийка','','','','',16712172,'','','','Elfe de la nuit','Nachtelf','','','','','Elfo de la noche','Elfo de la noche','Ночной эльф','','','','',16712172,'NORMAL','MARKINGS','NORMAL',0),
      (5,12,5,4142,57,58,'Sc',1,7,15007,1096,'Scourge',2,1,'Undead','Undead','언데드','Mort-vivant','Untoter','亡灵','亡灵','不死族','不死族','No-muerto','No-muerto','Нежить','','','','',16712191,'','','','Morte-vivante','Untote','','','','','No-muerta','No-muerta','Нежить','','','','',16712172,'','','','Mort-vivant','Untoter','','','','','No-muerto','No-muerto','','','','','',16712172,'FEATURES','FEATURES','NORMAL',0),
      (6,14,6,4143,59,60,'Ta',1,7,15007,1096,'Tauren',141,1,'Tauren','Tauren','타우렌','Tauren','Tauren','牛头人','牛头人','牛頭人','牛頭人','Tauren','Tauren','Таурен','','','','',16712191,'','','','Taurène','','','','','','Tauren','Tauren','','','','','',16712172,'','','','Tauren','Tauren','','','','','Tauren','Tauren','Таурен','','','','',16712172,'NORMAL','HAIR','HORNS',0),
      (7,12,115,4146,1563,1564,'Gn',7,7,15007,1096,'Gnome',101,0,'Gnome','Gnome','노움','Gnome','Gnom','侏儒','侏儒','地精','地精','Gnomo','Gnomo','Гном','','','','',16712190,'','','','Gnome','','','','','','Gnoma','Gnoma','','','','','',16712172,'','','','Gnome','Gnom','','','','','Gnomo','Gnomo','Гном','','','','',16712172,'NORMAL','EARRINGS','NORMAL',0),
      (8,14,116,4144,1478,1479,'Tr',1,7,15007,1096,'Troll',121,1,'Troll','Troll','트롤','Troll','Troll','巨魔','巨魔','食人妖','食人妖','Trol','Trol','Тролль','','','','',16712190,'','','','Trollesse','','','','','','Trol','Trol','','','','','',16712172,'','','','Troll','Troll','','','','','Trol','Trol','Тролль','','','','',16712172,'TUSKS','TUSKS','NORMAL',0),
      (9,1,1,0,6894,6895,'Go',7,7,15007,1096,'Goblin',0,2,'Goblin','Goblin','고블린','Gobelin','Goblin','地精','地精','哥布林','哥布林','Goblin','Goblin','Гоблин','','','','',16712190,'','','','Gobeline','','','','','','Goblin','Goblin','','','','','',16712172,'','','','Gobelin','Goblin','','','','','Goblin','Goblin','Гоблин','','','','',16712172,'NORMAL','NONE','NORMAL',0),
      (10,12,1610,4142,15476,15475,'Be',1,7,15007,1096,'BloodElf',162,1,'Blood Elf','Blood Elf','블러드 엘프','Elfe de sang','Blutelf','血精灵','血精灵','血精靈','血精靈','Elfo de sangre','Elfo de sangre','Эльф крови','','','','',16712190,'','','','Elfe de sang','Blutelfe','','','','','Elfa de sangre','Elfa de sangre','Эльфийка крови','','','','',16712172,'','','','Elfe de sang','Blutelf','','','','','Elfo de sangre','Elfo de sangre','Эльф крови','','','','',16712172,'NORMAL','EARRINGS','NORMAL',1),
      (11,14,1629,4140,16125,16126,'Dr',7,7,15007,1096,'Draenei',163,0,'Draenei','Draenei','드레나이','Draeneï','Draenei','德莱尼','德莱尼','德萊尼','德萊尼','Draenei','Draenei','Дреней','','','','',16712190,'','','','Draeneï','','','','','','Draenei','Draenei','','','','','',16712172,'','','','Draeneï','Draenei','','','','','Draenei','Draenei','Дреней','','','','',16712172,'NORMAL','HORNS','NORMAL',1),
      (12,5,1,0,16981,16980,'Fo',7,7,15007,1096,'FelOrc',0,2,'Fel Orc','Fel Orc','타락한 오크','Gangr''orc','Höllenorc','邪兽人','邪兽人','魔獄獸人','魔獄獸人','Orco vil','Orco vil','Орк Скверны','','','','',16712190,'','','','Gangr''orque','','','','','','Orco vil','Orco vil','','','','','',16712172,'','','','Gangr''orc','Höllenorc','','','','','Orco vil','Orco vil','Орк Скверны','','','','',16712172,'NORMAL','NORMAL','NORMAL',0),
      (13,1,1,0,17402,17403,'Na',7,7,15007,1096,'Naga_',0,2,'Naga','Naga','나가','Naga','Naga','纳迦','纳迦','納迦','納迦','Naga','Naga','Нага','','','','',16712190,'','','','Naga','','','','','','Naga','Naga','Нага','','','','',16712172,'','','','Naga','Naga','','','','','Naga','Naga','Наг','','','','',16712172,'Normal','Normal','Normal',0),
      (14,5,1,0,17576,17577,'Br',7,7,15007,1096,'Broken',0,2,'Broken','Broken','뒤틀린 드레나이','Roué','Zerschlagener','破碎者','破碎者','破碎者','破碎者','Tábido','Tábido','Падший','','','','',16712190,'','','','Rouée','','','','','','Tábida','Tábida','Падшая','','','','',16712172,'','','','Roué','Zerschlagener','','','','','Tábido','Tábido','Падший','','','','',16712172,'Normal','Normal','Normal',0),
      (15,1,1,0,17578,17579,'Sk',7,7,15007,1096,'Skeleton',0,2,'Skeleton','Skeleton','해골','Squelette','Skelett','骷髅','骷髅','骷髏','骷髏','Esqueleto','Esqueleto','Скелет','','','','',16712190,'','','','Squelette','','','','','','Esqueleto','Esqueleto','','','','','',16712172,'','','','Squelette','Skelett','','','','','Esqueleto','Esqueleto','Скелет','','','','',16712172,'Normal','Normal','Normal',0),
      (16,9,1,0,21685,21686,'Vr',7,7,15007,1096,'Vrykul',0,2,'Vrykul','Vrykul','브리쿨','Vrykul','Vrykul','维库人','维库人','維酷人','維酷人','Vrykul','Vrykul','Врайкул','','','','',16712190,'','','','Vrykule','','','','','','Vrykul','Vrykul','','','','','',16712172,'','','','Vrykul','Vrykul','','','','','Vrykul','Vrykul','Врайкул','','','','',16712172,'Normal','Normal','Normal',0),
      (17,1,1,0,21780,21781,'Tu',7,7,15007,1096,'Tuskarr',0,2,'Tuskarr','Tuskarr','투스카르','Rohart','Tuskarr','海象人','海象人','巨牙海民','巨牙海民','Colmillarr','Colmillarr','Клыкарр','','','','',16712190,'','','','Rohart','','','','','','Colmillarr','Colmillarr','','','','','',16712172,'','','','Rohart','Tuskarr','','','','','Colmillarr','Colmillarr','Клыкарр','','','','',16712172,'Normal','Normal','Normal',0),
      (18,15,1,0,21963,21964,'Ft',7,7,15007,1096,'ForestTroll',0,2,'Forest Troll','Forest Troll','숲 트롤','Troll des forêts','Waldtroll','森林巨魔','森林巨魔','森林食人妖','森林食人妖','Trol de bosque','Trol de bosque','Лесной тролль','','','','',16712190,'','','','Trollesse des forêts','','','','','','Trol de bosque','Trol de bosque','','','','','',16712172,'','','','Troll des forêts','Waldtroll','','','','','Trol de bosque','Trol de bosque','Лесной тролль','','','','',16712172,'TUSKS','TUSKS','Normal',0),
      (19,5,1,0,26316,26317,'Wt',7,7,15007,1096,'Taunka',0,2,'Taunka','Taunka','타운카','Taunka','Taunka','牦牛人','牦牛人','坦卡族','坦卡族','Taunka','Taunka','Таунка','','','','',16712190,'','','','Taunka','','','','','','Taunka','Taunka','Таунка','','','','',16712172,'','','','Taunka','Taunka','','','','','Taunka','Taunka','Таунка','','','','',16712172,'Normal','Normal','Normal',0),
      (20,5,1,0,26871,26872,'NS',7,7,15007,1096,'NorthrendSkeleton',0,2,'Northrend Skeleton','Northrend Skeleton','노스렌드 해골','Squelette du Norfendre','Skelett aus Nordend','诺森德骷髅','诺森德骷髅','北裂境骷髏','北裂境骷髏','Esqueleto de Rasganorte','Esqueleto de Rasganorte','Нордскольский скелет','','','','',16712190,'','','','Squelette du Norfendre','','','','','','Esqueleto de Rasganorte','Esqueleto de Rasganorte','','','','','',16712172,'','','','Squelette du Norfendre','Skelett aus Nordend','','','','','Esqueleto de Rasganorte','Esqueleto de Rasganorte','Нордскольский скелет','','','','',16712172,'Normal','Normal','Normal',0),
      (21,5,1,0,26873,26874,'It',7,7,15007,1096,'IceTroll',0,2,'Ice Troll','Ice Troll','얼음 트롤','Troll des glaces','Eistroll','冰巨魔','冰巨魔','寒冰食人妖','寒冰食人妖','Trol de hielo','Trol de hielo','Ледяной тролль','','','','',16712190,'','','','Trollesse des glaces','','','','','','Trol de hielo','Trol de hielo','','','','','',16712172,'','','','Troll des glaces','Eistroll','','','','','Trol de hielo','Trol de hielo','Ледяной тролль','','','','',16712172,'Normal','Normal','Normal',0);