DROP TABLE IF EXISTS dbc.dbc_mailtemplate;

CREATE TABLE dbc.dbc_mailtemplate
(
    id                 integer PRIMARY KEY DEFAULT 0,
    subject_lang_en_us text,
    subject_lang_en_gb text,
    subject_lang_ko_kr text,
    subject_lang_fr_fr text,
    subject_lang_de_de text,
    subject_lang_en_cn text,
    subject_lang_zh_cn text,
    subject_lang_en_tw text,
    subject_lang_zh_tw text,
    subject_lang_es_es text,
    subject_lang_es_mx text,
    subject_lang_ru_ru text,
    subject_lang_pt_pt text,
    subject_lang_pt_br text,
    subject_lang_it_it text,
    subject_lang_unk   text,
    subject_lang_mask  integer NOT NULL    DEFAULT 0,
    body_lang_en_us    text,
    body_lang_en_gb    text,
    body_lang_ko_kr    text,
    body_lang_fr_fr    text,
    body_lang_de_de    text,
    body_lang_en_cn    text,
    body_lang_zh_cn    text,
    body_lang_en_tw    text,
    body_lang_zh_tw    text,
    body_lang_es_es    text,
    body_lang_es_mx    text,
    body_lang_ru_ru    text,
    body_lang_pt_pt    text,
    body_lang_pt_br    text,
    body_lang_it_it    text,
    body_lang_unk      text,
    body_lang_mask     integer NOT NULL    DEFAULT 0
);
