DROP TABLE IF EXISTS dbc.dbc_lfgdungeons;

CREATE TABLE dbc.dbc_lfgdungeons
(
    id                    integer PRIMARY KEY DEFAULT 0,
    name_lang_enus        text,
    name_lang_engb        text,
    name_lang_kokr        text,
    name_lang_frfr        text,
    name_lang_dede        text,
    name_lang_encn        text,
    name_lang_zhcn        text,
    name_lang_entw        text,
    name_lang_zhtw        text,
    name_lang_eses        text,
    name_lang_esmx        text,
    name_lang_ruru        text,
    name_lang_ptpt        text,
    name_lang_ptbr        text,
    name_lang_itit        text,
    name_lang_unk         text,
    name_lang_mask        bigint  NOT NULL    DEFAULT 0,
    min_level             integer NOT NULL    DEFAULT 0,
    max_level             integer NOT NULL    DEFAULT 0,
    target_level          integer NOT NULL    DEFAULT 0,
    target_level_min      integer NOT NULL    DEFAULT 0,
    target_level_max      integer NOT NULL    DEFAULT 0,
    mapid                 integer NOT NULL    DEFAULT 0,
    difficulty            integer NOT NULL    DEFAULT 0,
    flags                 integer NOT NULL    DEFAULT 0,
    typeid                integer NOT NULL    DEFAULT 0,
    faction               integer NOT NULL    DEFAULT 0,
    texturefilename       text,
    expansionlevel        integer NOT NULL    DEFAULT 0,
    order_index           integer NOT NULL    DEFAULT 0,
    group_id              integer NOT NULL    DEFAULT 0,
    description_lang_enus text,
    description_lang_engb text,
    description_lang_kokr text,
    description_lang_frfr text,
    description_lang_dede text,
    description_lang_encn text,
    description_lang_zhcn text,
    description_lang_entw text,
    description_lang_zhtw text,
    description_lang_eses text,
    description_lang_esmx text,
    description_lang_ruru text,
    description_lang_ptpt text,
    description_lang_ptbr text,
    description_lang_itit text,
    description_lang_unk  text,
    description_lang_mask bigint  NOT NULL    DEFAULT 0
);
