DROP TABLE IF EXISTS dbc.dbc_map;

CREATE TABLE dbc.dbc_map
(
    id                         integer PRIMARY KEY DEFAULT 0,
    directory                  text,
    instance_type              integer NOT NULL    DEFAULT 0,
    flags                      integer NOT NULL    DEFAULT 0,
    pvp                        integer NOT NULL    DEFAULT 0,

    mapname_lang_en_us         text,
    mapname_lang_en_gb         text,
    mapname_lang_ko_kr         text,
    mapname_lang_fr_fr         text,
    mapname_lang_de_de         text,
    mapname_lang_en_cn         text,
    mapname_lang_zh_cn         text,
    mapname_lang_en_tw         text,
    mapname_lang_zh_tw         text,
    mapname_lang_es_es         text,
    mapname_lang_es_mx         text,
    mapname_lang_ru_ru         text,
    mapname_lang_pt_pt         text,
    mapname_lang_pt_br         text,
    mapname_lang_it_it         text,
    mapname_lang_unk           text,
    mapname_lang_mask          integer NOT NULL    DEFAULT 0,

    area_table_id              integer NOT NULL    DEFAULT 0,

    mapdescription0_lang_en_us text,
    mapdescription0_lang_en_gb text,
    mapdescription0_lang_ko_kr text,
    mapdescription0_lang_fr_fr text,
    mapdescription0_lang_de_de text,
    mapdescription0_lang_en_cn text,
    mapdescription0_lang_zh_cn text,
    mapdescription0_lang_en_tw text,
    mapdescription0_lang_zh_tw text,
    mapdescription0_lang_es_es text,
    mapdescription0_lang_es_mx text,
    mapdescription0_lang_ru_ru text,
    mapdescription0_lang_pt_pt text,
    mapdescription0_lang_pt_br text,
    mapdescription0_lang_it_it text,
    mapdescription0_lang_unk   text,
    mapdescription0_lang_mask  integer NOT NULL    DEFAULT 0,

    mapdescription1_lang_en_us text,
    mapdescription1_lang_en_gb text,
    mapdescription1_lang_ko_kr text,
    mapdescription1_lang_fr_fr text,
    mapdescription1_lang_de_de text,
    mapdescription1_lang_en_cn text,
    mapdescription1_lang_zh_cn text,
    mapdescription1_lang_en_tw text,
    mapdescription1_lang_zh_tw text,
    mapdescription1_lang_es_es text,
    mapdescription1_lang_es_mx text,
    mapdescription1_lang_ru_ru text,
    mapdescription1_lang_pt_pt text,
    mapdescription1_lang_pt_br text,
    mapdescription1_lang_it_it text,
    mapdescription1_lang_unk   text,
    mapdescription1_lang_mask  integer NOT NULL    DEFAULT 0,

    loading_screen_id          integer NOT NULL    DEFAULT 0,
    minimap_icon_scale         float4  NOT NULL    DEFAULT 0,
    corpse_map_id              integer NOT NULL    DEFAULT 0,
    corpse_x                   float4  NOT NULL    DEFAULT 0,
    corpse_y                   float4  NOT NULL    DEFAULT 0,
    time_of_day_override       integer NOT NULL    DEFAULT 0,
    expansion_id               integer NOT NULL    DEFAULT 0,
    raid_offset                integer NOT NULL    DEFAULT 0,
    max_players                integer NOT NULL    DEFAULT 0
);
