DROP TABLE IF EXISTS dbc.dbc_holidays;

CREATE TABLE dbc.dbc_holidays
(
    id                   integer PRIMARY KEY DEFAULT 0,
    duration_1           integer NOT NULL    DEFAULT 0,
    duration_2           integer NOT NULL    DEFAULT 0,
    duration_3           integer NOT NULL    DEFAULT 0,
    duration_4           integer NOT NULL    DEFAULT 0,
    duration_5           integer NOT NULL    DEFAULT 0,
    duration_6           integer NOT NULL    DEFAULT 0,
    duration_7           integer NOT NULL    DEFAULT 0,
    duration_8           integer NOT NULL    DEFAULT 0,
    duration_9           integer NOT NULL    DEFAULT 0,
    duration_10          integer NOT NULL    DEFAULT 0,
    date_1               integer NOT NULL    DEFAULT 0,
    date_2               integer NOT NULL    DEFAULT 0,
    date_3               integer NOT NULL    DEFAULT 0,
    date_4               integer NOT NULL    DEFAULT 0,
    date_5               integer NOT NULL    DEFAULT 0,
    date_6               integer NOT NULL    DEFAULT 0,
    date_7               integer NOT NULL    DEFAULT 0,
    date_8               integer NOT NULL    DEFAULT 0,
    date_9               integer NOT NULL    DEFAULT 0,
    date_10              integer NOT NULL    DEFAULT 0,
    date_11              integer NOT NULL    DEFAULT 0,
    date_12              integer NOT NULL    DEFAULT 0,
    date_13              integer NOT NULL    DEFAULT 0,
    date_14              integer NOT NULL    DEFAULT 0,
    date_15              integer NOT NULL    DEFAULT 0,
    date_16              integer NOT NULL    DEFAULT 0,
    date_17              integer NOT NULL    DEFAULT 0,
    date_18              integer NOT NULL    DEFAULT 0,
    date_19              integer NOT NULL    DEFAULT 0,
    date_20              integer NOT NULL    DEFAULT 0,
    date_21              integer NOT NULL    DEFAULT 0,
    date_22              integer NOT NULL    DEFAULT 0,
    date_23              integer NOT NULL    DEFAULT 0,
    date_24              integer NOT NULL    DEFAULT 0,
    date_25              integer NOT NULL    DEFAULT 0,
    date_26              integer NOT NULL    DEFAULT 0,
    region               integer NOT NULL    DEFAULT 0,
    looping              integer NOT NULL    DEFAULT 0,
    calendarflags_1      integer NOT NULL    DEFAULT 0,
    calendarflags_2      integer NOT NULL    DEFAULT 0,
    calendarflags_3      integer NOT NULL    DEFAULT 0,
    calendarflags_4      integer NOT NULL    DEFAULT 0,
    calendarflags_5      integer NOT NULL    DEFAULT 0,
    calendarflags_6      integer NOT NULL    DEFAULT 0,
    calendarflags_7      integer NOT NULL    DEFAULT 0,
    calendarflags_8      integer NOT NULL    DEFAULT 0,
    calendarflags_9      integer NOT NULL    DEFAULT 0,
    calendarflags_10     integer NOT NULL    DEFAULT 0,
    holidaynameid        integer NOT NULL    DEFAULT 0,
    holidaydescriptionid integer NOT NULL    DEFAULT 0,
    texturefilename      text,
    priority             integer NOT NULL    DEFAULT 0,
    calendarfiltertype   integer NOT NULL    DEFAULT 0,
    flags                integer NOT NULL    DEFAULT 0
);
