DROP TABLE IF EXISTS dbc.dbc_chartitles;

CREATE TABLE dbc.dbc_chartitles
(
    id              INTEGER NOT NULL DEFAULT 0,
    condition_id    INTEGER NOT NULL DEFAULT 0,
    name_lang_enus  TEXT,
    name_lang_engb  TEXT,
    name_lang_kokr  TEXT,
    name_lang_frfr  TEXT,
    name_lang_dede  TEXT,
    name_lang_encn  TEXT,
    name_lang_zhcn  TEXT,
    name_lang_entw  TEXT,
    name_lang_zhtw  TEXT,
    name_lang_eses  TEXT,
    name_lang_esmx  TEXT,
    name_lang_ruru  TEXT,
    name_lang_ptpt  TEXT,
    name_lang_ptbr  TEXT,
    name_lang_itit  TEXT,
    name_lang_unk   TEXT,
    name_lang_mask  BIGINT  NOT NULL DEFAULT 0,
    name1_lang_enus TEXT,
    name1_lang_engb TEXT,
    name1_lang_kokr TEXT,
    name1_lang_frfr TEXT,
    name1_lang_dede TEXT,
    name1_lang_encn TEXT,
    name1_lang_zhcn TEXT,
    name1_lang_entw TEXT,
    name1_lang_zhtw TEXT,
    name1_lang_eses TEXT,
    name1_lang_esmx TEXT,
    name1_lang_ruru TEXT,
    name1_lang_ptpt TEXT,
    name1_lang_ptbr TEXT,
    name1_lang_itit TEXT,
    name1_lang_unk  TEXT,
    name1_lang_mask BIGINT  NOT NULL DEFAULT 0,
    mask_id         INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT pk_dbc_chartitles PRIMARY KEY (id)
);