DROP TABLE IF EXISTS dbc.dbc_chrclasses;

CREATE TABLE dbc.dbc_chrclasses
(
    ID                    INTEGER NOT NULL DEFAULT 0,
    Field01               INTEGER NOT NULL DEFAULT 0,
    DisplayPower          INTEGER NOT NULL DEFAULT 0,
    PetNameToken          INTEGER NOT NULL DEFAULT 0,
    Name_Lang_enUS        TEXT,
    Name_Lang_enGB        TEXT,
    Name_Lang_koKR        TEXT,
    Name_Lang_frFR        TEXT,
    Name_Lang_deDE        TEXT,
    Name_Lang_enCN        TEXT,
    Name_Lang_zhCN        TEXT,
    Name_Lang_enTW        TEXT,
    Name_Lang_zhTW        TEXT,
    Name_Lang_esES        TEXT,
    Name_Lang_esMX        TEXT,
    Name_Lang_ruRU        TEXT,
    Name_Lang_ptPT        TEXT,
    Name_Lang_ptBR        TEXT,
    Name_Lang_itIT        TEXT,
    Name_Lang_Unk         TEXT,
    Name_Lang_Mask        INTEGER NOT NULL DEFAULT 0,
    Name_Female_Lang_enUS TEXT,
    Name_Female_Lang_enGB TEXT,
    Name_Female_Lang_koKR TEXT,
    Name_Female_Lang_frFR TEXT,
    Name_Female_Lang_deDE TEXT,
    Name_Female_Lang_enCN TEXT,
    Name_Female_Lang_zhCN TEXT,
    Name_Female_Lang_enTW TEXT,
    Name_Female_Lang_zhTW TEXT,
    Name_Female_Lang_esES TEXT,
    Name_Female_Lang_esMX TEXT,
    Name_Female_Lang_ruRU TEXT,
    Name_Female_Lang_ptPT TEXT,
    Name_Female_Lang_ptBR TEXT,
    Name_Female_Lang_itIT TEXT,
    Name_Female_Lang_Unk  TEXT,
    Name_Female_Lang_Mask INTEGER NOT NULL DEFAULT 0,
    Name_Male_Lang_enUS   TEXT,
    Name_Male_Lang_enGB   TEXT,
    Name_Male_Lang_koKR   TEXT,
    Name_Male_Lang_frFR   TEXT,
    Name_Male_Lang_deDE   TEXT,
    Name_Male_Lang_enCN   TEXT,
    Name_Male_Lang_zhCN   TEXT,
    Name_Male_Lang_enTW   TEXT,
    Name_Male_Lang_zhTW   TEXT,
    Name_Male_Lang_esES   TEXT,
    Name_Male_Lang_esMX   TEXT,
    Name_Male_Lang_ruRU   TEXT,
    Name_Male_Lang_ptPT   TEXT,
    Name_Male_Lang_ptBR   TEXT,
    Name_Male_Lang_itIT   TEXT,
    Name_Male_Lang_Unk    TEXT,
    Name_Male_Lang_Mask   INTEGER NOT NULL DEFAULT 0,
    Filename              TEXT,
    SpellClassSet         INTEGER NOT NULL DEFAULT 0,
    Flags                 INTEGER NOT NULL DEFAULT 0,
    CinematicSequenceID   INTEGER NOT NULL DEFAULT 0,
    Required_Expansion    INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

INSERT INTO dbc.dbc_chrclasses (
    id, field01, displaypower, petnametoken,
    name_lang_enus, name_lang_engb, name_lang_kokr, name_lang_frfr, name_lang_dede,
    name_lang_encn, name_lang_zhcn, name_lang_entw, name_lang_zhtw,
    name_lang_eses, name_lang_esmx, name_lang_ruru, name_lang_ptpt, name_lang_ptbr, name_lang_itit,
    name_lang_unk, name_lang_mask,
    name_female_lang_enus, name_female_lang_engb, name_female_lang_kokr, name_female_lang_frfr, name_female_lang_dede,
    name_female_lang_encn, name_female_lang_zhcn, name_female_lang_entw, name_female_lang_zhtw,
    name_female_lang_eses, name_female_lang_esmx, name_female_lang_ruru, name_female_lang_ptpt, name_female_lang_ptbr, name_female_lang_itit,
    name_female_lang_unk, name_female_lang_mask,
    name_male_lang_enus, name_male_lang_engb, name_male_lang_kokr, name_male_lang_frfr, name_male_lang_dede,
    name_male_lang_encn, name_male_lang_zhcn, name_male_lang_entw, name_male_lang_zhtw,
    name_male_lang_eses, name_male_lang_esmx, name_male_lang_ruru, name_male_lang_ptpt, name_male_lang_ptbr, name_male_lang_itit,
    name_male_lang_unk, name_male_lang_mask,
    filename, spellclassset, flags, cinematicsequenceid, required_expansion
) VALUES
      (1, 0, 1, 1, 'Warrior', 'Warrior', '전사', 'Guerrier', 'Krieger', '战士', '战士', '戰士', '戰士', 'Guerrero', 'Guerrero', 'Воин', '', '', '', '', 16712191, '', '', '', 'Guerrière', 'Kriegerin', '', '', '', '', 'Guerrera', 'Guerrera', '', '', '', '', '', 16712172, '', '', '', 'Guerrier', 'Krieger', '', '', '', '', 'Guerrero', 'Guerrero', 'Воин', '', '', '', '', 16712172, 'WARRIOR', 4, 50, 0, 0),
      (2, 0, 0, 1, 'Paladin', 'Paladin', '성기사', 'Paladin', 'Paladin', '圣骑士', '圣骑士', '聖騎士', '聖騎士', 'Paladín', 'Paladín', 'Паладин', '', '', '', '', 16712191, '', '', '', '', '', '', '', '', '', 'Paladín', 'Paladín', '', '', '', '', '', 16712172, '', '', '', 'Paladin', 'Paladin', '', '', '', '', 'Paladín', 'Paladín', 'Паладин', '', '', '', '', 16712172, 'PALADIN', 10, 58, 0, 0),
      (3, 1, 0, 1, 'Hunter', 'Hunter', '사냥꾼', 'Chasseur', 'Jäger', '猎人', '猎人', '獵人', '獵人', 'Cazador', 'Cazador', 'Охотник', '', '', '', '', 16712191, '', '', '', 'Chasseresse', 'Jägerin', '', '', '', '', 'Cazadora', 'Cazadora', 'Охотница', '', '', '', '', 16712172, '', '', '', 'Chasseur', 'Jäger', '', '', '', '', 'Cazador', 'Cazador', 'Охотник', '', '', '', '', 16712172, 'HUNTER', 9, 22, 0, 0),
      (4, 1, 3, 1, 'Rogue', 'Rogue', '도적', 'Voleur', 'Schurke', '潜行者', '潜行者', '盜賊', '盜賊', 'Pícaro', 'Pícaro', 'Разбойник', '', '', '', '', 16712191, '', '', '', 'Voleuse', 'Schurkin', '', '', '', '', 'Pícara', 'Pícara', 'Разбойница', '', '', '', '', 16712172, '', '', '', 'Voleur', 'Schurke', '', '', '', '', 'Pícaro', 'Pícaro', 'Разбойник', '', '', '', '', 16712172, 'ROGUE', 8, 2, 0, 0),
      (5, 0, 0, 1, 'Priest', 'Priest', '사제', 'Prêtre', 'Priester', '牧师', '牧师', '牧師', '牧師', 'Sacerdote', 'Sacerdote', 'Жрец', '', '', '', '', 16712191, '', '', '', 'Prêtresse', 'Priesterin', '', '', '', '', 'Sacerdotisa', 'Sacerdotisa', 'Жрица', '', '', '', '', 16712172, '', '', '', 'Prêtre', 'Priester', '', '', '', '', 'Sacerdote', 'Sacerdote', 'Жрец', '', '', '', '', 16712172, 'PRIEST', 6, 2, 0, 0),
      (6, 9, 6, 1, 'Death Knight', 'Death Knight', '죽음의 기사', 'Chevalier de la mort', 'Todesritter', '死亡骑士', '死亡骑士', '死亡騎士', '死亡騎士', 'Caballero de la Muerte', 'Caballero de la Muerte', 'Рыцарь смерти', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', 'Caballero de la Muerte', 'Caballero de la Muerte', '', '', '', '', '', 16712172, '', '', '', 'Chevalier de la mort', 'Todesritter', '', '', '', '', 'Caballero de la Muerte', 'Caballero de la Muerte', 'Рыцарь смерти', '', '', '', '', 16712172, 'DEATHKNIGHT', 15, 122, 165, 2),
      (7, 1, 0, 1, 'Shaman', 'Shaman', '주술사', 'Chaman', 'Schamane', '萨满祭司', '萨满祭司', '薩滿', '薩滿', 'Chamán', 'Chamán', 'Шаман', '', '', '', '', 16712191, '', '', '', 'Chamane', 'Schamanin', '', '', '', '', 'Chamán', 'Chamán', 'Шаманка', '', '', '', '', 16712172, '', '', '', 'Chaman', 'Schamane', '', '', '', '', 'Chamán', 'Chamán', 'Шаман', '', '', '', '', 16712172, 'SHAMAN', 11, 26, 0, 0),
      (8, 0, 0, 1, 'Mage', 'Mage', '마법사', 'Mage', 'Magier', '法师', '法师', '法師', '法師', 'Mago', 'Mago', 'Маг', '', '', '', '', 16712191, '', '', '', 'Mage', 'Magierin', '', '', '', '', 'Maga', 'Maga', '', '', '', '', '', 16712172, '', '', '', 'Mage', 'Magier', '', '', '', '', 'Mago', 'Mago', 'Маг', '', '', '', '', 16712172, 'MAGE', 3, 2, 0, 0),
      (9, 0, 0, 126, 'Warlock', 'Warlock', '흑마법사', 'Démoniste', 'Hexenmeister', '术士', '术士', '術士', '術士', 'Brujo', 'Brujo', 'Чернокнижник', '', '', '', '', 16712191, '', '', '', 'Démoniste', 'Hexenmeisterin', '', '', '', '', 'Bruja', 'Bruja', 'Чернокнижница', '', '', '', '', 16712172, '', '', '', 'Démoniste', 'Hexenmeister', '', '', '', '', 'Brujo', 'Brujo', 'Чернокнижник', '', '', '', '', 16712172, 'WARLOCK', 5, 6, 0, 0),
      (11, 0, 0, 1, 'Druid', 'Druid', '드루이드', 'Druide', 'Druide', '德鲁伊', '德鲁伊', '德魯伊', '德魯伊', 'Druida', 'Druida', 'Друид', '', '', '', '', 16712191, '', '', '', 'Druidesse', 'Druidin', '', '', '', '', 'Druida', 'Druida', '', '', '', '', '', 16712172, '', '', '', 'Druide', 'Druide', '', '', '', '', 'Druida', 'Druida', 'Друид', '', '', '', '', 16712172, 'DRUID', 7, 10, 0, 0);