DROP TABLE IF EXISTS dbc.dbc_spellrange;

CREATE TABLE dbc.dbc_spellrange
(
    ID                         INTEGER NOT NULL DEFAULT 0,
    RangeMin_1                 REAL    NOT NULL DEFAULT 0,
    RangeMin_2                 REAL    NOT NULL DEFAULT 0,
    RangeMax_1                 REAL    NOT NULL DEFAULT 0,
    RangeMax_2                 REAL    NOT NULL DEFAULT 0,
    Flags                      INTEGER NOT NULL DEFAULT 0,
    DisplayName_Lang_enUS      TEXT             DEFAULT NULL,
    DisplayName_Lang_enGB      TEXT             DEFAULT NULL,
    DisplayName_Lang_koKR      TEXT             DEFAULT NULL,
    DisplayName_Lang_frFR      TEXT             DEFAULT NULL,
    DisplayName_Lang_deDE      TEXT             DEFAULT NULL,
    DisplayName_Lang_enCN      TEXT             DEFAULT NULL,
    DisplayName_Lang_zhCN      TEXT             DEFAULT NULL,
    DisplayName_Lang_enTW      TEXT             DEFAULT NULL,
    DisplayName_Lang_zhTW      TEXT             DEFAULT NULL,
    DisplayName_Lang_esES      TEXT             DEFAULT NULL,
    DisplayName_Lang_esMX      TEXT             DEFAULT NULL,
    DisplayName_Lang_ruRU      TEXT             DEFAULT NULL,
    DisplayName_Lang_ptPT      TEXT             DEFAULT NULL,
    DisplayName_Lang_ptBR      TEXT             DEFAULT NULL,
    DisplayName_Lang_itIT      TEXT             DEFAULT NULL,
    DisplayName_Lang_Unk       TEXT             DEFAULT NULL,
    DisplayName_Lang_Mask      INTEGER NOT NULL DEFAULT 0,
    DisplayNameShort_Lang_enUS TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_enGB TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_koKR TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_frFR TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_deDE TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_enCN TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_zhCN TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_enTW TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_zhTW TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_esES TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_esMX TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_ruRU TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_ptPT TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_ptBR TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_itIT TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_Unk  TEXT             DEFAULT NULL,
    DisplayNameShort_Lang_Mask INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (ID)
);

INSERT INTO dbc.dbc_spellrange (ID, RangeMin_1, RangeMin_2, RangeMax_1, RangeMax_2, Flags,
                                DisplayName_Lang_enUS, DisplayName_Lang_enGB, DisplayName_Lang_koKR,
                                DisplayName_Lang_frFR, DisplayName_Lang_deDE,
                                DisplayName_Lang_enCN, DisplayName_Lang_zhCN, DisplayName_Lang_enTW,
                                DisplayName_Lang_zhTW, DisplayName_Lang_esES,
                                DisplayName_Lang_esMX, DisplayName_Lang_ruRU, DisplayName_Lang_ptPT,
                                DisplayName_Lang_ptBR, DisplayName_Lang_itIT,
                                DisplayName_Lang_Unk, DisplayName_Lang_Mask,
                                DisplayNameShort_Lang_enUS, DisplayNameShort_Lang_enGB, DisplayNameShort_Lang_koKR,
                                DisplayNameShort_Lang_frFR,
                                DisplayNameShort_Lang_deDE, DisplayNameShort_Lang_enCN, DisplayNameShort_Lang_zhCN,
                                DisplayNameShort_Lang_enTW,
                                DisplayNameShort_Lang_zhTW, DisplayNameShort_Lang_esES, DisplayNameShort_Lang_esMX,
                                DisplayNameShort_Lang_ruRU,
                                DisplayNameShort_Lang_ptPT, DisplayNameShort_Lang_ptBR, DisplayNameShort_Lang_itIT,
                                DisplayNameShort_Lang_Unk,
                                DisplayNameShort_Lang_Mask)
VALUES (1, 0.0, 0.0, 0.0, 0.0, 0, 'Self Only', 'Self Only', '자신', 'Personnel', 'Nur selbst', '自身', '自身',
        'Self Only', 'Self Only', 'Self Only', 'Self Only', 'Self Only', '', '', '', '', 4259902, 'Self', 'Self',
        'Self', 'Soi-même', 'Selbst', '自身', '自身', 'Self', 'Self', 'Self', 'Self', 'Self', '', '', '', '', 4259900),
       (2, 0.0, 0.0, 5.0, 5.0, 1, 'Combat Range', 'Combat Range', '근접거리', 'Portée de combat', 'Kampf-Reichweite',
        '作战范围', '作战范围', 'Combat Range', 'Combat Range', 'Combat Range', 'Combat Range', 'Combat Range', '', '',
        '', '', 12648510, 'Combat', 'Combat', 'Combat', 'Combat', 'Kampf', '作战范围', '作战范围', 'Combat', 'Combat',
        'Combat', 'Combat', 'Combat', '', '', '', '', 12648508),
       (3, 0.0, 0.0, 20.0, 20.0, 0, 'Twenty yards', 'Twenty yards', '단거리', 'Portée courte', 'Kurze Reichweite', '较近',
        '较近', 'Short Range', 'Short Range', 'Twenty yards', 'Twenty yards', 'Twenty yards', '', '', '', '', 4259902,
        'Short', 'Short', 'Short', 'Court', 'Kurz', '较近', '较近', 'Short', 'Short', 'Short', 'Short', 'Short', '', '',
        '', '', 4259900),
       (4, 0.0, 0.0, 30.0, 30.0, 0, 'Medium Range', 'Medium Range', '중거리', 'Portée moyenne', 'Mittlere Reichweite',
        '中程', '中程', 'Medium Range', 'Medium Range', 'Medium Range', 'Medium Range', 'Medium Range', '', '', '', '',
        4259902, 'Medium', 'Medium', 'Medium', 'Moyen', 'Mittel', '中程', '中程', 'Medium', 'Medium', 'Medium',
        'Medium', 'Medium', '', '', '', '', 4259900),
       (5, 0.0, 0.0, 40.0, 40.0, 0, 'Long Range', 'Long Range', '장거리', 'Portée longue', 'Lange Reichweite', '较远',
        '较远', 'Long Range', 'Long Range', 'Long Range', 'Long Range', 'Long Range', '', '', '', '', 4259902, 'Long',
        'Long', 'Long', 'Long', 'Lang', '较远', '较远', 'Long', 'Long', 'Long', 'Long', 'Long', '', '', '', '',
        4259900),
       (6, 0.0, 0.0, 100.0, 100.0, 0, 'Vision Range', 'Vision Range', '시야거리', 'Portée de vue', 'Sichtweite', '视野范围',
        '视野范围', 'Vision Range', 'Vision Range', 'Vision Range', 'Vision Range', 'Vision Range', '', '', '', '',
        4259902, 'Vision', 'Vision', 'Vision', 'Vision', 'Sicht', '视野范围', '视野范围', 'Vision', 'Vision', 'Vision',
        'Vision', 'Vision', '', '', '', '', 4259900),
       (7, 0.0, 0.0, 10.0, 10.0, 0, 'Ten yards', 'Ten yards', '최단거리', 'Portée très courte', 'Sehr kurze Reichweite',
        '近身', '近身', 'Very Short Range', 'Very Short Range', 'Ten yards', 'Ten yards', 'Ten yards', '', '', '', '',
        4259902, 'Very Short', 'Very Short', 'Very Short', 'Très court', 'Sehr kurz', '近身', '近身', 'Very Short',
        'Very Short', 'Very Short', 'Very Short', 'Very Short', '', '', '', '', 4259900),
       (8, 10.0, 10.0, 20.0, 20.0, 0, 'Min Range 10, 20', 'Min Range 10, 20', '단거리', 'Portée courte',
        'Kurze Reichweite', '较近', '较近', 'Short Range', 'Short Range', 'Min Range 10, 20', 'Min Range 10, 20',
        'Min Range 10, 20', '', '', '', '', 4259902, 'Short', 'Short', 'Short', 'Court', 'Kurz', '较近', '较近',
        'Short', 'Short', 'Short', 'Short', 'Short', '', '', '', '', 4259900),
       (9, 10.0, 10.0, 30.0, 30.0, 0, 'Medium Range', 'Medium Range', '중거리', 'Portée moyenne', 'Mittlere Reichweite',
        '中程', '中程', 'Medium Range', 'Medium Range', 'Medium Range', 'Medium Range', 'Medium Range', '', '', '', '',
        4259902, 'Medium', 'Medium', 'Medium', 'Moyen', 'Mittel', '中程', '中程', 'Medium', 'Medium', 'Medium',
        'Medium', 'Medium', '', '', '', '', 4259900),
       (10, 10.0, 10.0, 40.0, 40.0, 0, 'Long Range', 'Long Range', '장거리', 'Portée longue', 'Lange Reichweite', '较远',
        '较远', 'Long Range', 'Long Range', 'Long Range', 'Long Range', 'Long Range', '', '', '', '', 4259902, 'Long',
        'Long', 'Long', 'Long', 'Lang', '较远', '较远', 'Long', 'Long', 'Long', 'Long', 'Long', '', '', '', '',
        4259900),
       (11, 0.0, 0.0, 15.0, 15.0, 0, 'Fifteen yards', 'Fifteen yards', '단거리', 'Portée courte', 'Kürzere Reichweite',
        '近程', '近程', 'Shorter Range', 'Shorter Range', 'Fifteen yards', 'Fifteen yards', 'Fifteen yards', '', '', '',
        '', 4259902, 'Shorter', 'Shorter', 'Shorter', 'Plus court', 'Kürzer', '近程', '近程', 'Shorter', 'Shorter',
        'Shorter', 'Shorter', 'Shorter', '', '', '', '', 4259900),
       (12, 0.0, 0.0, 5.0, 5.0, 0, 'Interact Range', 'Interact Range', '작용거리', 'Portée d''interaction',
        'Interaktion-Reichweite', '交互范围', '交互范围', 'Interact Range', 'Interact Range', 'Interact Range',
        'Interact Range', 'Interact Range', '', '', '', '', 4259902, 'Interact', 'Interact', 'Interact', 'Interagir',
        'Interaktion', '交互范围', '交互范围', 'Interact', 'Interact', 'Interact', 'Interact', 'Interact', '', '', '',
        '', 4259900),
       (13, 0.0, 0.0, 50000.0, 50000.0, 0, 'Anywhere', 'Anywhere', '거리제한 없음', 'Partout', 'Irgendwo', '任意地点',
        '任意地点', 'Anywhere', 'Anywhere', 'Anywhere', 'Anywhere', 'Anywhere', '', '', '', '', 4259902, 'Anywhere',
        'Anywhere', 'Anywhere', 'Partout', 'Irgendwo', '任意地点', '任意地点', 'Anywhere', 'Anywhere', 'Anywhere',
        'Anywhere', 'Anywhere', '', '', '', '', 4259900),
       (14, 0.0, 0.0, 60.0, 60.0, 0, 'Extra Long Range', 'Extra Long Range', '최장거리', 'Portée très longue',
        'Extralange Reichweite', '超远程', '超远程', 'Extra Long Range', 'Extra Long Range', 'Extra Long Range',
        'Extra Long Range', 'Extra Long Range', '', '', '', '', 4259902, 'Extra Long', 'Extra Long', 'Extra Long',
        'Extra-long', 'Extralang', '超远程', '超远程', 'Extra Long', 'Extra Long', 'Extra Long', 'Extra Long',
        'Extra Long', '', '', '', '', 4259900),
       (34, 0.0, 0.0, 25.0, 25.0, 0, 'Twenty-Five yards', 'Twenty-Five yards', '중단거리', 'Portée courte-moyenne',
        'Mittelkurze Reichweite', '中近程', '中近程', 'Medium-Short Range', 'Medium-Short Range', 'Twenty-Five yards',
        'Twenty-Five yards', 'Twenty-Five yards', '', '', '', '', 4259902, 'Medium-Short', 'Medium-Short',
        'Medium-Short', 'Moyen-court', 'Mittelkurz', '中近程', '中近程', 'Medium-Short', 'Medium-Short', 'Medium-Short',
        'Medium-Short', 'Medium-Short', '', '', '', '', 4259900),
       (35, 0.0, 0.0, 35.0, 35.0, 0, 'Medium-Long Range', 'Medium-Long Range', '중장거리', 'Portée moyenne-longue',
        'Mittellange Reichweite', '中远程', '中远程', 'Medium-Long Range', 'Medium-Long Range', 'Medium-Long Range',
        'Medium-Long Range', 'Medium-Long Range', '', '', '', '', 4259902, 'Medium-Long', 'Medium-Long', 'Medium-Long',
        'Moyen-long', 'Mittellang', '中远程', '中远程', 'Medium-Long', 'Medium-Long', 'Medium-Long', 'Medium-Long',
        'Medium-Long', '', '', '', '', 4259900),
       (36, 0.0, 0.0, 45.0, 45.0, 0, 'Longer Range', 'Longer Range', 'Longer Range', 'Portée longue',
        'Längere Reichweite', '远程', '远程', 'Longer Range', 'Longer Range', 'Longer Range', 'Longer Range',
        'Longer Range', '', '', '', '', 4259900, 'Longer', 'Longer', 'Longer', 'Plus long', 'Länger', '远程', '远程',
        'Longer', 'Longer', 'Longer', 'Longer', 'Longer', '', '', '', '', 4259900),
       (37, 0.0, 0.0, 50.0, 50.0, 0, 'Extended Range', 'Extended Range', 'Extended Range', 'Portée étendue',
        'Verlängerte Reichweite', '延长范围', '延长范围', 'Extended Range', 'Extended Range', 'Extended Range',
        'Extended Range', 'Extended Range', '', '', '', '', 4259900, 'Extended', 'Extended', 'Extended', 'Etendu',
        'Vergrößert', '延长范围', '延长范围', 'Extended', 'Extended', 'Extended', 'Extended', 'Extended', '', '', '',
        '', 4259900),
       (38, 10.0, 10.0, 25.0, 25.0, 0, 'Min-Range 10, 25', 'Min-Range 10, 25', 'Min-Range 10, 25',
        'Portée moyenne étendue', 'Extramittlere Reichweite', '额外中程', '额外中程', 'Extra Medium Range',
        'Extra Medium Range', 'Min-Range 10, 25', 'Min-Range 10, 25', 'Min-Range 10, 25', '', '', '', '', 4259900,
        'Extra Medium', 'Extra Medium', 'Extra Medium', 'Extra-moyen', 'Extramittel', '额外中程', '额外中程',
        'Extra Medium', 'Extra Medium', 'Extra Medium', 'Extra Medium', 'Extra Medium', '', '', '', '', 4259900),
       (54, 5.0, 5.0, 30.0, 30.0, 0, 'Monster Shoot', 'Monster Shoot', 'Monster Shoot', 'Tir monstrueux de Geoff',
        'Geoff Monster-Schuss', 'Geoff Monster Shoot', 'Geoff Monster Shoot', 'Geoff Monster Shoot',
        'Geoff Monster Shoot', 'Monster Shoot', 'Monster Shoot', 'Monster Shoot', '', '', '', '', 2031676,
        'Monster Shoot Range', 'Monster Shoot Range', 'Monster Shoot Range', 'Geoff', 'Geoff', 'Geoff', 'Geoff',
        'Geoff', 'Geoff', 'Monster Shoot Range', 'Monster Shoot Range', 'Monster Shoot Range', '', '', '', '', 2031676),
       (74, 0.0, 0.0, 30.0, 30.0, 2, 'Ranged Weapon', 'Ranged Weapon', 'Ranged Weapon', 'Arme à distance',
        'Distanzwaffe', 'Ranged Weapon', 'Ranged Weapon', 'Ranged Weapon', 'Ranged Weapon', 'Ranged Weapon',
        'Ranged Weapon', 'Ranged Weapon', '', '', '', '', 2031676, 'Ranged', 'Ranged', 'Ranged', 'A distance',
        'Distanz', 'Ranged', 'Ranged', 'Ranged', 'Ranged', 'Ranged', 'Ranged', 'Ranged', '', '', '', '', 2031676),
       (94, 8.0, 8.0, 40.0, 40.0, 0, 'Sting', 'Sting', 'Sting', 'Aiguillon', 'Stich', 'Sting', 'Sting', 'Sting',
        'Sting', 'Sting', 'Sting', 'Sting', '', '', '', '', 2031676, 'Sting', 'Sting', 'Sting', 'Aiguillon', 'Stich',
        'Sting', 'Sting', 'Sting', 'Sting', 'Sting', 'Sting', 'Sting', '', '', '', '', 2031676),
       (95, 8.0, 8.0, 25.0, 25.0, 0, 'Charge', 'Charge', 'Charge', 'Charge', 'Aufladen', 'Charge', 'Charge', 'Charge',
        'Charge', 'Charge', 'Charge', 'Charge', '', '', '', '', 2031676, 'Charge', 'Charge', 'Charge', 'Charge',
        'Aufladen', 'Charge', 'Charge', 'Charge', 'Charge', 'Charge', 'Charge', 'Charge', '', '', '', '', 2031676),
       (96, 0.0, 0.0, 2.0, 2.0, 0, 'Trap', 'Trap', 'Trap', 'Piège', 'Falle', 'Trap', 'Trap', 'Trap', 'Trap', 'Trap',
        'Trap', 'Trap', '', '', '', '', 2031676, 'Trap', 'Trap', 'Trap', 'Piège', 'Falle', 'Trap', 'Trap', 'Trap',
        'Trap', 'Trap', 'Trap', 'Trap', '', '', '', '', 2031676),
       (114, 0.0, 0.0, 35.0, 35.0, 2, 'Hunter Range', 'Hunter Range', 'Hunter Range', 'Portée du Chasseur',
        'Jägerreichweite', 'Hunter Range', 'Hunter Range', 'Hunter Range', 'Hunter Range', 'Hunter Range',
        'Hunter Range', 'Hunter Range', '', '', '', '', 2031676, 'Hunter', 'Hunter', 'Hunter', 'Chasseur', 'Hunter',
        'Hunter', 'Hunter', 'Hunter', 'Hunter', 'Hunter', 'Hunter', 'Hunter', '', '', '', '', 2031668),
       (134, 0.0, 0.0, 80.0, 80.0, 0, 'Tower 80', 'Tower 80', 'Tower 80', 'Tower 80', 'Tower 80', 'Tower 80',
        'Tower 80', 'Tower 80', 'Tower 80', 'Tower 80', 'Tower 80', 'Tower 80', '', '', '', '', 2031664, 'Tower',
        'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', '', '', '',
        '', 2031664),
       (135, 0.0, 0.0, 100.0, 100.0, 0, 'Tower 100', 'Tower 100', 'Tower 100', 'Tower 100', 'Tower 100', 'Tower 100',
        'Tower 100', 'Tower 100', 'Tower 100', 'Tower 100', 'Tower 100', 'Tower 100', '', '', '', '', 2031664, 'Tower',
        'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', 'Tower', '', '', '',
        '', 2031664),
       (136, 30.0, 30.0, 80.0, 80.0, 0, 'Thirty-to-80', 'Thirty-to-80', 'Thirty-to-80', 'Thirty-to-80', 'Thirty-to-80',
        'Thirty-to-80', 'Thirty-to-80', 'Artillery Range', 'Artillery Range', 'Thirty-to-80', 'Thirty-to-80',
        'Thirty-to-80', '', '', '', '', 1507360, 'Thirty-to-80', 'Thirty-to-80', 'Thirty-to-80', 'Thirty-to-80',
        'Thirty-to-80', 'Thirty-to-80', 'Thirty-to-80', 'Artillery', 'Artillery', 'Thirty-to-80', 'Thirty-to-80',
        'Thirty-to-80', '', '', '', '', 1507360),
       (137, 0.0, 0.0, 8.0, 8.0, 0, 'Eight yards', 'Eight yards', 'Eight yards', 'Eight yards', 'Eight yards',
        'Eight yards', 'Eight yards', 'Very Short Range', 'Very Short Range', 'Eight yards', 'Eight yards',
        'Eight yards', '', '', '', '', 1507360, 'Very Short', 'Very Short', 'Very Short', 'Very Short', 'Very Short',
        'Very Short', 'Very Short', 'Very Short', 'Very Short', 'Very Short', 'Very Short', 'Very Short', '', '', '',
        '', 1507360),
       (139, 5.0, 5.0, 45.0, 45.0, 0, 'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot',
        'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot',
        'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot',
        'Long Range Hunter Shoot', '', '', '', '', 65536, 'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long',
        'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long',
        'Hunter Long', '', '', '', '', 65536),
       (140, 0.0, 0.0, 6.0, 6.0, 0, 'Six yards', 'Six yards', 'Six yards', 'Six yards', 'Six yards', 'Six yards',
        'Six yards', 'Six yards', 'Six yards', 'Six yards', 'Six yards', 'Six yards', '', '', '', '', 65536,
        'Six yards', 'Six yards', 'Six yards', 'Six yards', 'Six yards', 'Six yards', 'Six yards', 'Six yards',
        'Six yards', 'Six yards', 'Six yards', 'Six yards', '', '', '', '', 65536),
       (141, 0.0, 0.0, 7.0, 7.0, 0, 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards',
        'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', '', '',
        '', '', 65536, 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards',
        'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', 'Seven yards', '', '', '', '',
        65536),
       (150, 8.0, 8.0, 100.0, 100.0, 0, 'Valgarde 8/100', 'Valgarde 8/100', 'Valgarde 8/100', 'Valgarde 8/100',
        'Valgarde 8/100', 'Valgarde 8/100', 'Valgarde 8/100', 'Valgarde 8/100', 'Valgarde 8/100', 'Valgarde 8/100',
        'Valgarde 8/100', 'Valgarde 8/100', '', '', '', '', 65536, 'Valgarde', 'Valgarde', 'Valgarde', 'Valgarde',
        'Valgarde', 'Valgarde', 'Valgarde', 'Valgarde', 'Valgarde', 'Valgarde', 'Valgarde', 'Valgarde', '', '', '', '',
        65536),
       (151, 5.0, 5.0, 45.0, 45.0, 0, 'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot',
        'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot',
        'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot', 'Long Range Hunter Shoot',
        'Long Range Hunter Shoot', '', '', '', '', 65536, 'Hunter 45', 'Hunter 45', 'Hunter 45', 'Hunter 45',
        'Hunter 45', 'Hunter 45', 'Hunter 45', 'Hunter 45', 'Hunter 45', 'Hunter 45', 'Hunter 45', 'Hunter 45', '', '',
        '', '', 65536),
       (152, 0.0, 0.0, 150.0, 150.0, 0, 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long',
        'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', '', '', '',
        '', 65536, 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long',
        'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', '', '', '', '', 65536),
       (153, 0.0, 0.0, 60.0, 60.0, 0, 'Charge, 60', 'Charge, 60', 'Charge, 60', 'Charge, 60', 'Charge, 60',
        'Charge, 60', 'Charge, 60', 'Charge, 60', 'Charge, 60', 'Charge, 60', 'Charge, 60', 'Charge, 60', '', '', '',
        '', 65536, 'Huge Charge', 'Huge Charge', 'Huge Charge', 'Huge Charge', 'Huge Charge', 'Huge Charge',
        'Huge Charge', 'Huge Charge', 'Huge Charge', 'Huge Charge', 'Huge Charge', 'Huge Charge', '', '', '', '',
        65536),
       (154, 10.0, 10.0, 80.0, 80.0, 0, 'Tower 80, 10', 'Tower 80, 10', 'Tower 80, 10', 'Tower 80, 10', 'Tower 80, 10',
        'Tower 80, 10', 'Tower 80, 10', 'Tower 80, 10', 'Tower 80, 10', 'Tower 80, 10', 'Tower 80, 10', 'Tower 80, 10',
        '', '', '', '', 65536, 'Tower 10', 'Tower 10', 'Tower 10', 'Tower 10', 'Tower 10', 'Tower 10', 'Tower 10',
        'Tower 10', 'Tower 10', 'Tower 10', 'Tower 10', 'Tower 10', '', '', '', '', 65536),
       (155, 0.0, 0.0, 45.0, 45.0, 2, 'Hunter Range (Long)', 'Hunter Range (Long)', 'Hunter Range (Long)',
        'Hunter Range (Long)', 'Hunter Range (Long)', 'Hunter Range (Long)', 'Hunter Range (Long)',
        'Hunter Range (Long)', 'Hunter Range (Long)', 'Hunter Range (Long)', 'Hunter Range (Long)',
        'Hunter Range (Long)', '', '', '', '', 65536, 'Hunter (Long)', 'Hunter (Long)', 'Hunter (Long)',
        'Hunter (Long)', 'Hunter (Long)', 'Hunter (Long)', 'Hunter (Long)', 'Hunter (Long)', 'Hunter (Long)',
        'Hunter (Long)', 'Hunter (Long)', 'Hunter (Long)', '', '', '', '', 65536),
       (156, 30.0, 30.0, 200.0, 200.0, 0, 'Boulder Range', 'Boulder Range', 'Boulder Range', 'Boulder Range',
        'Boulder Range', 'Boulder Range', 'Boulder Range', 'Boulder Range', 'Boulder Range', 'Boulder Range',
        'Boulder Range', 'Boulder Range', '', '', '', '', 65536, 'Boulder', 'Boulder', 'Boulder', 'Boulder', 'Boulder',
        'Boulder', 'Boulder', 'Boulder', 'Boulder', 'Boulder', 'Boulder', 'Boulder', '', '', '', '', 65536),
       (157, 0.0, 0.0, 90.0, 90.0, 0, 'Ninety', 'Ninety', 'Ninety', 'Ninety', 'Ninety', 'Ninety', 'Ninety', 'Ninety',
        'Ninety', 'Ninety', 'Ninety', 'Ninety', '', '', '', '', 65536, 'Ninety', 'Ninety', 'Ninety', 'Ninety', 'Ninety',
        'Ninety', 'Ninety', 'Ninety', 'Ninety', 'Ninety', 'Ninety', 'Ninety', '', '', '', '', 65536),
       (158, 15.0, 15.0, 150.0, 150.0, 0, 'Super Long, 15 Min', 'Super Long, 15 Min', 'Super Long, 15 Min',
        'Super Long, 15 Min', 'Super Long, 15 Min', 'Super Long, 15 Min', 'Super Long, 15 Min', 'Super Long, 15 Min',
        'Super Long, 15 Min', 'Super Long, 15 Min', 'Super Long, 15 Min', 'Super Long, 15 Min', '', '', '', '', 65536,
        'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long',
        'Super Long', 'Super Long', 'Super Long', 'Super Long', '', '', '', '', 65536),
       (159, 0.0, 0.0, 40.0, 100.0, 0, 'TEST - Long Range', 'TEST - Long Range', 'TEST - Long Range',
        'TEST - Long Range', 'TEST - Long Range', 'TEST - Long Range', 'TEST - Long Range', 'TEST - Long Range',
        'TEST - Long Range', 'TEST - Long Range', 'TEST - Long Range', 'TEST - Long Range', '', '', '', '', 65536,
        'TestLong', 'TestLong', 'TestLong', 'TestLong', 'TestLong', 'TestLong', 'TestLong', 'TestLong', 'TestLong',
        'TestLong', 'TestLong', 'TestLong', '', '', '', '', 65536),
       (160, 0.0, 0.0, 30.0, 40.0, 0, 'Medium/Long Range', 'Medium/Long Range', 'Medium/Long Range',
        'Medium/Long Range', 'Medium/Long Range', 'Medium/Long Range', 'Medium/Long Range', 'Medium/Long Range',
        'Medium/Long Range', 'Medium/Long Range', 'Medium/Long Range', 'Medium/Long Range', '', '', '', '', 65536,
        'Medium/Long', 'Medium/Long', 'Medium/Long', 'Medium/Long', 'Medium/Long', 'Medium/Long', 'Medium/Long',
        'Medium/Long', 'Medium/Long', 'Medium/Long', 'Medium/Long', 'Medium/Long', '', '', '', '', 65536),
       (161, 0.0, 0.0, 20.0, 40.0, 0, 'Short/Long Range', 'Short/Long Range', 'Short/Long Range', 'Short/Long Range',
        'Short/Long Range', 'Short/Long Range', 'Short/Long Range', 'Short/Long Range', 'Short/Long Range',
        'Short/Long Range', 'Short/Long Range', 'Short/Long Range', '', '', '', '', 65536, 'Short/Long', 'Short/Long',
        'Short/Long', 'Short/Long', 'Short/Long', 'Short/Long', 'Short/Long', 'Short/Long', 'Short/Long', 'Short/Long',
        'Short/Long', 'Short/Long', '', '', '', '', 65536),
       (162, 0.0, 0.0, 20.0, 30.0, 0, 'Medium/Short Range', 'Medium/Short Range', 'Medium/Short Range',
        'Medium/Short Range', 'Medium/Short Range', 'Medium/Short Range', 'Medium/Short Range', 'Medium/Short Range',
        'Medium/Short Range', 'Medium/Short Range', 'Medium/Short Range', 'Medium/Short Range', '', '', '', '', 65536,
        'Medium/Short', 'Medium/Short', 'Medium/Short', 'Medium/Short', 'Medium/Short', 'Medium/Short', 'Medium/Short',
        'Medium/Short', 'Medium/Short', 'Medium/Short', 'Medium/Short', 'Medium/Short', '', '', '', '', 65536),
       (163, 8.0, 8.0, 30.0, 30.0, 0, 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip',
        'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', '', '', '',
        '', 65536, 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip',
        'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', 'Death Grip', '', '', '', '', 65536),
       (164, 10.0, 10.0, 70.0, 70.0, 0, 'Catapult Range', 'Catapult Range', 'Catapult Range', 'Catapult Range',
        'Catapult Range', 'Catapult Range', 'Catapult Range', 'Catapult Range', 'Catapult Range', 'Catapult Range',
        'Catapult Range', 'Catapult Range', '', '', '', '', 65536, 'Catapult', 'Catapult', 'Catapult', 'Catapult',
        'Catapult', 'Catapult', 'Catapult', 'Catapult', 'Catapult', 'Catapult', 'Catapult', 'Catapult', '', '', '', '',
        65536),
       (165, 0.0, 0.0, 14.0, 14.0, 0, 'Fourteen yards', 'Fourteen yards', 'Fourteen yards', 'Fourteen yards',
        'Fourteen yards', 'Fourteen yards', 'Fourteen yards', 'Fourteen yards', 'Fourteen yards', 'Fourteen yards',
        'Fourteen yards', 'Fourteen yards', '', '', '', '', 65536, 'Shorter', 'Shorter', 'Shorter', 'Shorter',
        'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', '', '', '', '', 65536),
       (166, 0.0, 0.0, 13.0, 13.0, 0, 'Thirteen yards', 'Thirteen yards', 'Thirteen yards', 'Thirteen yards',
        'Thirteen yards', 'Thirteen yards', 'Thirteen yards', 'Thirteen yards', 'Thirteen yards', 'Thirteen yards',
        'Thirteen yards', 'Thirteen yards', '', '', '', '', 65536, 'Shorter', 'Shorter', 'Shorter', 'Shorter',
        'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', '', '', '', '', 65536),
       (167, 40.0, 0.0, 150.0, 150.0, 0, 'Super Long (Min Range)', 'Super Long (Min Range)', 'Super Long (Min Range)',
        'Super Long (Min Range)', 'Super Long (Min Range)', 'Super Long (Min Range)', 'Super Long (Min Range)',
        'Super Long (Min Range)', 'Super Long (Min Range)', 'Super Long (Min Range)', 'Super Long (Min Range)',
        'Super Long (Min Range)', '', '', '', '', 0, 'Super Long', 'Super Long', 'Super Long', 'Super Long',
        'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long', 'Super Long',
        '', '', '', '', 0),
       (168, 0.0, 0.0, 38.0, 38.0, 0, 'Medium-Long Range (38)', 'Medium-Long Range (38)', 'Medium-Long Range (38)',
        'Medium-Long Range (38)', 'Medium-Long Range (38)', 'Medium-Long Range (38)', 'Medium-Long Range (38)',
        'Medium-Long Range (38)', 'Medium-Long Range (38)', 'Medium-Long Range (38)', 'Medium-Long Range (38)',
        'Medium-Long Range (38)', '', '', '', '', 0, 'Medium-Long', 'Medium-Long', 'Medium-Long', 'Medium-Long',
        'Medium-Long', 'Medium-Long', 'Medium-Long', 'Medium-Long', 'Medium-Long', 'Medium-Long', 'Medium-Long',
        'Medium-Long', '', '', '', '', 0),
       (169, 0.0, 0.0, 3.0, 3.0, 0, 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards',
        'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', '', '',
        '', '', 0, 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards',
        'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', 'Three Yards', '', '', '', '', 0),
       (170, 0.0, 0.0, 55.0, 55.0, 0, 'Fifty Five Yards', 'Fifty Five Yards', 'Fifty Five Yards', 'Fifty Five Yards',
        'Fifty Five Yards', 'Fifty Five Yards', 'Fifty Five Yards', 'Fifty Five Yards', 'Fifty Five Yards',
        'Fifty Five Yards', 'Fifty Five Yards', 'Fifty Five Yards', '', '', '', '', 0, 'Extended', 'Extended',
        'Extended', 'Extended', 'Extended', 'Extended', 'Extended', 'Extended', 'Extended', 'Extended', 'Extended',
        'Extended', '', '', '', '', 0),
       (171, 1.0, 1.0, 10.0, 10.0, 0, 'Min Range 1, 10', 'Min Range 1, 10', 'Min Range 1, 10', 'Min Range 1, 10',
        'Min Range 1, 10', 'Min Range 1, 10', 'Min Range 1, 10', 'Min Range 1, 10', 'Min Range 1, 10',
        'Min Range 1, 10', 'Min Range 1, 10', 'Min Range 1, 10', '', '', '', '', 0, 'Very Short', 'Very Short',
        'Very Short', 'Very Short', 'Very Short', 'Very Short', 'Very Short', 'Very Short', 'Very Short', 'Very Short',
        'Very Short', 'Very Short', '', '', '', '', 0),
       (172, 0.0, 0.0, 11.0, 11.0, 0, 'Eleven yards', 'Eleven yards', 'Eleven yards', 'Eleven yards', 'Eleven yards',
        'Eleven yards', 'Eleven yards', 'Eleven yards', 'Eleven yards', 'Eleven yards', 'Eleven yards', 'Eleven yards',
        '', '', '', '', 0, 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter',
        'Shorter', 'Shorter', 'Shorter', 'Shorter', '', '', '', '', 0),
       (173, 5.0, 5.0, 50000.0, 50000.0, 0, 'Anywhere (Combat Min Range)', 'Anywhere (Combat Min Range)',
        'Anywhere (Combat Min Range)', 'Anywhere (Combat Min Range)', 'Anywhere (Combat Min Range)',
        'Anywhere (Combat Min Range)', 'Anywhere (Combat Min Range)', 'Anywhere (Combat Min Range)',
        'Anywhere (Combat Min Range)', 'Anywhere (Combat Min Range)', 'Anywhere (Combat Min Range)',
        'Anywhere (Combat Min Range)', '', '', '', '', 0, 'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long',
        'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long', 'Hunter Long',
        'Hunter Long', '', '', '', '', 0),
       (174, 0.0, 0.0, 1000.0, 1000.0, 0, 'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A',
        'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A', '', '', '', '', 0, 'U L T R A',
        'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A', 'U L T R A',
        'U L T R A', 'U L T R A', 'U L T R A', '', '', '', '', 0),
       (176, 0.0, 0.0, 70.0, 70.0, 0, 'Seventy yards', 'Seventy yards', 'Seventy yards', 'Seventy yards',
        'Seventy yards', 'Seventy yards', 'Seventy yards', 'Seventy yards', 'Seventy yards', 'Seventy yards',
        'Seventy yards', 'Seventy yards', '', '', '', '', 0, 'Extended', 'Extended', 'Extended', 'Extended', 'Extended',
        'Extended', 'Extended', 'Extended', 'Extended', 'Extended', 'Extended', 'Extended', '', '', '', '', 0),
       (177, 20.0, 20.0, 70.0, 70.0, 0, 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70',
        'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', '', '',
        '', '', 0, 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70',
        'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', 'Donut 20-70', '', '', '', '', 0),
       (179, 5.0, 5.0, 15.0, 15.0, 0, 'Min Range 5, 15', 'Min Range 5, 15', 'Min Range 5, 15', 'Min Range 5, 15',
        'Min Range 5, 15', 'Min Range 5, 15', 'Min Range 5, 15', 'Min Range 5, 15', 'Min Range 5, 15',
        'Min Range 5, 15', 'Min Range 5, 15', 'Min Range 5, 15', '', '', '', '', 0, 'Shorter', 'Shorter', 'Shorter',
        'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', 'Shorter', '', '', '',
        '', 0),
       (180, 5.0, 5.0, 25.0, 25.0, 0, 'Tournament - Ranged', 'Tournament - Ranged', 'Tournament - Ranged',
        'Tournament - Ranged', 'Tournament - Ranged', 'Tournament - Ranged', 'Tournament - Ranged',
        'Tournament - Ranged', 'Tournament - Ranged', 'Tournament - Ranged', 'Tournament - Ranged',
        'Tournament - Ranged', '', '', '', '', 0, 'Argent Tournament - Ranged', 'Argent Tournament - Ranged',
        'Argent Tournament - Ranged', 'Argent Tournament - Ranged', 'Argent Tournament - Ranged',
        'Argent Tournament - Ranged', 'Argent Tournament - Ranged', 'Argent Tournament - Ranged',
        'Argent Tournament - Ranged', 'Argent Tournament - Ranged', 'Argent Tournament - Ranged',
        'Argent Tournament - Ranged', '', '', '', '', 0),
       (181, 0.0, 0.0, 200.0, 200.0, 0, 'Two-Hundred Yard Range', 'Two-Hundred Yard Range', 'Two-Hundred Yard Range',
        'Two-Hundred Yard Range', 'Two-Hundred Yard Range', 'Two-Hundred Yard Range', 'Two-Hundred Yard Range',
        'Two-Hundred Yard Range', 'Two-Hundred Yard Range', 'Two-Hundred Yard Range', 'Two-Hundred Yard Range',
        'Two-Hundred Yard Range', '', '', '', '', 0, '200', '200', '200', '200', '200', '200', '200', '200', '200',
        '200', '200', '200', '', '', '', '', 0),
       (184, 5.0, 5.0, 25.0, 25.0, 0, 'Min Range 5, 25', 'Min Range 5, 25', 'Min Range 5, 25', 'Min Range 5, 25',
        'Min Range 5, 25', 'Min Range 5, 25', 'Min Range 5, 25', 'Min Range 5, 25', 'Min Range 5, 25',
        'Min Range 5, 25', 'Min Range 5, 25', 'Min Range 5, 25', '', '', '', '', 0, 'Medium', 'Medium', 'Medium',
        'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', 'Medium', '', '', '', '', 0),
       (187, 0.0, 0.0, 300.0, 300.0, 0, 'Three Hundred Yards', 'Three Hundred Yards', 'Three Hundred Yards',
        'Three Hundred Yards', 'Three Hundred Yards', 'Three Hundred Yards', 'Three Hundred Yards',
        'Three Hundred Yards', 'Three Hundred Yards', 'Three Hundred Yards', 'Three Hundred Yards',
        'Three Hundred Yards', '', '', '', '', 0, '300', '300', '300', '300', '300', '300', '300', '300', '300', '300',
        '300', '300', '', '', '', '', 0);