DROP TABLE IF EXISTS dbc.dbc_spell;

CREATE TABLE dbc.dbc_spell
(
    id                         int8             NOT NULL,
    category                   int8   DEFAULT 0 NOT NULL,
    dispeltype                 int8   DEFAULT 0 NOT NULL,
    mechanic                   int8   DEFAULT 0 NOT NULL,
    "attributes"               int8   DEFAULT 0 NOT NULL,
    attributesex               int8   DEFAULT 0 NOT NULL,
    attributesexb              int8   DEFAULT 0 NOT NULL,
    attributesexc              int8   DEFAULT 0 NOT NULL,
    attributesexd              int8   DEFAULT 0 NOT NULL,
    attributesexe              int8   DEFAULT 0 NOT NULL,
    attributesexf              int8   DEFAULT 0 NOT NULL,
    attributesexg              int8   DEFAULT 0 NOT NULL,
    shapeshiftmask_1           int8   DEFAULT 0 NOT NULL,
    shapeshiftmask_2           int8   DEFAULT 0 NOT NULL,
    shapeshiftexclude_1        int8   DEFAULT 0 NOT NULL,
    shapeshiftexclude_2        int8   DEFAULT 0 NOT NULL,
    targets                    int8   DEFAULT 0 NOT NULL,
    targetcreaturetype         int8   DEFAULT 0 NOT NULL,
    requiresspellfocus         int8   DEFAULT 0 NOT NULL,
    facingcasterflags          int8   DEFAULT 0 NOT NULL,
    casteraurastate            int8   DEFAULT 0 NOT NULL,
    targetaurastate            int8   DEFAULT 0 NOT NULL,
    excludecasteraurastate     int8   DEFAULT 0 NOT NULL,
    excludetargetaurastate     int8   DEFAULT 0 NOT NULL,
    casterauraspell            int8   DEFAULT 0 NOT NULL,
    targetauraspell            int8   DEFAULT 0 NOT NULL,
    excludecasterauraspell     int8   DEFAULT 0 NOT NULL,
    excludetargetauraspell     int8   DEFAULT 0 NOT NULL,
    castingtimeindex           int8   DEFAULT 0 NOT NULL,
    recoverytime               int8   DEFAULT 0 NOT NULL,
    categoryrecoverytime       int8   DEFAULT 0 NOT NULL,
    interruptflags             int8   DEFAULT 0 NOT NULL,
    aurainterruptflags         int8   DEFAULT 0 NOT NULL,
    channelinterruptflags      int8   DEFAULT 0 NOT NULL,
    proctypemask               int8   DEFAULT 0 NOT NULL,
    procchance                 int8   DEFAULT 0 NOT NULL,
    proccharges                int8   DEFAULT 0 NOT NULL,
    maxlevel                   int8   DEFAULT 0 NOT NULL,
    baselevel                  int8   DEFAULT 0 NOT NULL,
    spelllevel                 int8   DEFAULT 0 NOT NULL,
    durationindex              int8   DEFAULT 0 NOT NULL,
    powertype                  int8   DEFAULT 0 NOT NULL,
    manacost                   int8   DEFAULT 0 NOT NULL,
    manacostperlevel           int8   DEFAULT 0 NOT NULL,
    manapersecond              int8   DEFAULT 0 NOT NULL,
    manapersecondperlevel      int8   DEFAULT 0 NOT NULL,
    rangeindex                 int8   DEFAULT 0 NOT NULL,
    speed                      float4 DEFAULT 0 NOT NULL,
    modalnextspell             int8   DEFAULT 0 NOT NULL,
    cumulativeaura             int8   DEFAULT 0 NOT NULL,
    totem_1                    int8   DEFAULT 0 NOT NULL,
    totem_2                    int8   DEFAULT 0 NOT NULL,
    reagent_1                  int8   DEFAULT 0 NOT NULL,
    reagent_2                  int8   DEFAULT 0 NOT NULL,
    reagent_3                  int8   DEFAULT 0 NOT NULL,
    reagent_4                  int8   DEFAULT 0 NOT NULL,
    reagent_5                  int8   DEFAULT 0 NOT NULL,
    reagent_6                  int8   DEFAULT 0 NOT NULL,
    reagent_7                  int8   DEFAULT 0 NOT NULL,
    reagent_8                  int8   DEFAULT 0 NOT NULL,
    reagentcount_1             int8   DEFAULT 0 NOT NULL,
    reagentcount_2             int8   DEFAULT 0 NOT NULL,
    reagentcount_3             int8   DEFAULT 0 NOT NULL,
    reagentcount_4             int8   DEFAULT 0 NOT NULL,
    reagentcount_5             int8   DEFAULT 0 NOT NULL,
    reagentcount_6             int8   DEFAULT 0 NOT NULL,
    reagentcount_7             int8   DEFAULT 0 NOT NULL,
    reagentcount_8             int8   DEFAULT 0 NOT NULL,
    equippeditemclass          int8   DEFAULT 0 NOT NULL,
    equippeditemsubclass       int8   DEFAULT 0 NOT NULL,
    equippediteminvtypes       int8   DEFAULT 0 NOT NULL,
    effect_1                   int8   DEFAULT 0 NOT NULL,
    effect_2                   int8   DEFAULT 0 NOT NULL,
    effect_3                   int8   DEFAULT 0 NOT NULL,
    effectdiesides_1           int8   DEFAULT 0 NOT NULL,
    effectdiesides_2           int8   DEFAULT 0 NOT NULL,
    effectdiesides_3           int8   DEFAULT 0 NOT NULL,
    effectrealpointsperlevel_1 float4 DEFAULT 0 NOT NULL,
    effectrealpointsperlevel_2 float4 DEFAULT 0 NOT NULL,
    effectrealpointsperlevel_3 float4 DEFAULT 0 NOT NULL,
    effectbasepoints_1         int8   DEFAULT 0 NOT NULL,
    effectbasepoints_2         int8   DEFAULT 0 NOT NULL,
    effectbasepoints_3         int8   DEFAULT 0 NOT NULL,
    effectmechanic_1           int8   DEFAULT 0 NOT NULL,
    effectmechanic_2           int8   DEFAULT 0 NOT NULL,
    effectmechanic_3           int8   DEFAULT 0 NOT NULL,
    implicittargeta_1          int8   DEFAULT 0 NOT NULL,
    implicittargeta_2          int8   DEFAULT 0 NOT NULL,
    implicittargeta_3          int8   DEFAULT 0 NOT NULL,
    implicittargetb_1          int8   DEFAULT 0 NOT NULL,
    implicittargetb_2          int8   DEFAULT 0 NOT NULL,
    implicittargetb_3          int8   DEFAULT 0 NOT NULL,
    effectradiusindex_1        int8   DEFAULT 0 NOT NULL,
    effectradiusindex_2        int8   DEFAULT 0 NOT NULL,
    effectradiusindex_3        int8   DEFAULT 0 NOT NULL,
    effectaura_1               int8   DEFAULT 0 NOT NULL,
    effectaura_2               int8   DEFAULT 0 NOT NULL,
    effectaura_3               int8   DEFAULT 0 NOT NULL,
    effectauraperiod_1         int8   DEFAULT 0 NOT NULL,
    effectauraperiod_2         int8   DEFAULT 0 NOT NULL,
    effectauraperiod_3         int8   DEFAULT 0 NOT NULL,
    effectamplitude_1          float4 DEFAULT 0 NOT NULL,
    effectamplitude_2          float4 DEFAULT 0 NOT NULL,
    effectamplitude_3          float4 DEFAULT 0 NOT NULL,
    effectchaintargets_1       int8   DEFAULT 0 NOT NULL,
    effectchaintargets_2       int8   DEFAULT 0 NOT NULL,
    effectchaintargets_3       int8   DEFAULT 0 NOT NULL,
    effectitemtype_1           int8   DEFAULT 0 NOT NULL,
    effectitemtype_2           int8   DEFAULT 0 NOT NULL,
    effectitemtype_3           int8   DEFAULT 0 NOT NULL,
    effectmiscvalue_1          int8   DEFAULT 0 NOT NULL,
    effectmiscvalue_2          int8   DEFAULT 0 NOT NULL,
    effectmiscvalue_3          int8   DEFAULT 0 NOT NULL,
    effectmiscvalueb_1         int8   DEFAULT 0 NOT NULL,
    effectmiscvalueb_2         int8   DEFAULT 0 NOT NULL,
    effectmiscvalueb_3         int8   DEFAULT 0 NOT NULL,
    effecttriggerspell_1       int8   DEFAULT 0 NOT NULL,
    effecttriggerspell_2       int8   DEFAULT 0 NOT NULL,
    effecttriggerspell_3       int8   DEFAULT 0 NOT NULL,
    effectpointspercombo_1     float4 DEFAULT 0 NOT NULL,
    effectpointspercombo_2     float4 DEFAULT 0 NOT NULL,
    effectpointspercombo_3     float4 DEFAULT 0 NOT NULL,
    effectspellclassmaska_1    int8   DEFAULT 0 NOT NULL,
    effectspellclassmaska_2    int8   DEFAULT 0 NOT NULL,
    effectspellclassmaska_3    int8   DEFAULT 0 NOT NULL,
    effectspellclassmaskb_1    int8   DEFAULT 0 NOT NULL,
    effectspellclassmaskb_2    int8   DEFAULT 0 NOT NULL,
    effectspellclassmaskb_3    int8   DEFAULT 0 NOT NULL,
    effectspellclassmaskc_1    int8   DEFAULT 0 NOT NULL,
    effectspellclassmaskc_2    int8   DEFAULT 0 NOT NULL,
    effectspellclassmaskc_3    int8   DEFAULT 0 NOT NULL,
    spellvisualid_1            int8   DEFAULT 0 NOT NULL,
    spellvisualid_2            int8   DEFAULT 0 NOT NULL,
    spelliconid                int8   DEFAULT 0 NOT NULL,
    activeiconid               int8   DEFAULT 0 NOT NULL,
    spellpriority              int8   DEFAULT 0 NOT NULL,
    name_lang_enus             text NULL,
    name_lang_engb             text NULL,
    name_lang_kokr             text NULL,
    name_lang_frfr             text NULL,
    name_lang_dede             text NULL,
    name_lang_encn             text NULL,
    name_lang_zhcn             text NULL,
    name_lang_entw             text NULL,
    name_lang_zhtw             text NULL,
    name_lang_eses             text NULL,
    name_lang_esmx             text NULL,
    name_lang_ruru             text NULL,
    name_lang_ptpt             text NULL,
    name_lang_ptbr             text NULL,
    name_lang_itit             text NULL,
    name_lang_unk              text NULL,
    name_lang_mask             int8   DEFAULT 0 NOT NULL,
    namesubtext_lang_enus      text NULL,
    namesubtext_lang_engb      text NULL,
    namesubtext_lang_kokr      text NULL,
    namesubtext_lang_frfr      text NULL,
    namesubtext_lang_dede      text NULL,
    namesubtext_lang_encn      text NULL,
    namesubtext_lang_zhcn      text NULL,
    namesubtext_lang_entw      text NULL,
    namesubtext_lang_zhtw      text NULL,
    namesubtext_lang_eses      text NULL,
    namesubtext_lang_esmx      text NULL,
    namesubtext_lang_ruru      text NULL,
    namesubtext_lang_ptpt      text NULL,
    namesubtext_lang_ptbr      text NULL,
    namesubtext_lang_itit      text NULL,
    namesubtext_lang_unk       text NULL,
    namesubtext_lang_mask      int8   DEFAULT 0 NOT NULL,
    description_lang_enus      text NULL,
    description_lang_engb      text NULL,
    description_lang_kokr      text NULL,
    description_lang_frfr      text NULL,
    description_lang_dede      text NULL,
    description_lang_encn      text NULL,
    description_lang_zhcn      text NULL,
    description_lang_entw      text NULL,
    description_lang_zhtw      text NULL,
    description_lang_eses      text NULL,
    description_lang_esmx      text NULL,
    description_lang_ruru      text NULL,
    description_lang_ptpt      text NULL,
    description_lang_ptbr      text NULL,
    description_lang_itit      text NULL,
    description_lang_unk       text NULL,
    description_lang_mask      int8   DEFAULT 0 NOT NULL,
    auradescription_lang_enus  text NULL,
    auradescription_lang_engb  text NULL,
    auradescription_lang_kokr  text NULL,
    auradescription_lang_frfr  text NULL,
    auradescription_lang_dede  text NULL,
    auradescription_lang_encn  text NULL,
    auradescription_lang_zhcn  text NULL,
    auradescription_lang_entw  text NULL,
    auradescription_lang_zhtw  text NULL,
    auradescription_lang_eses  text NULL,
    auradescription_lang_esmx  text NULL,
    auradescription_lang_ruru  text NULL,
    auradescription_lang_ptpt  text NULL,
    auradescription_lang_ptbr  text NULL,
    auradescription_lang_itit  text NULL,
    auradescription_lang_unk   text NULL,
    auradescription_lang_mask  int8   DEFAULT 0 NOT NULL,
    manacostpct                int8   DEFAULT 0 NOT NULL,
    startrecoverycategory      int8   DEFAULT 0 NOT NULL,
    startrecoverytime          int8   DEFAULT 0 NOT NULL,
    maxtargetlevel             int8   DEFAULT 0 NOT NULL,
    spellclassset              int8   DEFAULT 0 NOT NULL,
    spellclassmask_1           int8   DEFAULT 0 NOT NULL,
    spellclassmask_2           int8   DEFAULT 0 NOT NULL,
    spellclassmask_3           int8   DEFAULT 0 NOT NULL,
    maxtargets                 int8   DEFAULT 0 NOT NULL,
    defensetype                int8   DEFAULT 0 NOT NULL,
    preventiontype             int8   DEFAULT 0 NOT NULL,
    stancebarorder             int8   DEFAULT 0 NOT NULL,
    effectchainamplitude_1     float4 DEFAULT 0 NOT NULL,
    effectchainamplitude_2     float4 DEFAULT 0 NOT NULL,
    effectchainamplitude_3     float4 DEFAULT 0 NOT NULL,
    minfactionid               int8   DEFAULT 0 NOT NULL,
    minreputation              int8   DEFAULT 0 NOT NULL,
    requiredauravision         int8   DEFAULT 0 NOT NULL,
    requiredtotemcategoryid_1  int8   DEFAULT 0 NOT NULL,
    requiredtotemcategoryid_2  int8   DEFAULT 0 NOT NULL,
    requiredareasid            int8   DEFAULT 0 NOT NULL,
    schoolmask                 int8   DEFAULT 0 NOT NULL,
    runecostid                 int8   DEFAULT 0 NOT NULL,
    spellmissileid             int8   DEFAULT 0 NOT NULL,
    powerdisplayid             int8   DEFAULT 0 NOT NULL,
    effectbonuscoefficient_1   float4 DEFAULT 0 NOT NULL,
    effectbonuscoefficient_2   float4 DEFAULT 0 NOT NULL,
    effectbonuscoefficient_3   float4 DEFAULT 0 NOT NULL,
    spelldescriptionvariableid int8   DEFAULT 0 NOT NULL,
    spelldifficultyid          int8   DEFAULT 0 NOT NULL,
    CONSTRAINT dbc_spell_pkey PRIMARY KEY (id)
);