DROP TABLE IF EXISTS dbc.dbc_spellitemenchantment;

CREATE TABLE dbc.dbc_spellitemenchantment
(
    id                INTEGER PRIMARY KEY DEFAULT 0,
    charges           INTEGER NOT NULL    DEFAULT 0,
    effect_1          INTEGER NOT NULL    DEFAULT 0,
    effect_2          INTEGER NOT NULL    DEFAULT 0,
    effect_3          INTEGER NOT NULL    DEFAULT 0,
    effectpointsmin_1 INTEGER NOT NULL    DEFAULT 0,
    effectpointsmin_2 INTEGER NOT NULL    DEFAULT 0,
    effectpointsmin_3 INTEGER NOT NULL    DEFAULT 0,
    effectpointsmax_1 INTEGER NOT NULL    DEFAULT 0,
    effectpointsmax_2 INTEGER NOT NULL    DEFAULT 0,
    effectpointsmax_3 INTEGER NOT NULL    DEFAULT 0,
    effectarg_1       INTEGER NOT NULL    DEFAULT 0,
    effectarg_2       INTEGER NOT NULL    DEFAULT 0,
    effectarg_3       INTEGER NOT NULL    DEFAULT 0,
    name_lang_enus    TEXT,
    name_lang_engb    TEXT,
    name_lang_kokr    TEXT,
    name_lang_frfr    TEXT,
    name_lang_dede    TEXT,
    name_lang_encn    TEXT,
    name_lang_zhcn    TEXT,
    name_lang_entw    TEXT,
    name_lang_zhtw    TEXT,
    name_lang_eses    TEXT,
    name_lang_esmx    TEXT,
    name_lang_ruru    TEXT,
    name_lang_ptpt    TEXT,
    name_lang_ptbr    TEXT,
    name_lang_itit    TEXT,
    name_lang_unk     TEXT,
    name_lang_mask    BIGINT  NOT NULL    DEFAULT 0,
    itemvisual        INTEGER NOT NULL    DEFAULT 0,
    flags             INTEGER NOT NULL    DEFAULT 0,
    src_itemid        INTEGER NOT NULL    DEFAULT 0,
    condition_id      INTEGER NOT NULL    DEFAULT 0,
    requiredskillid   INTEGER NOT NULL    DEFAULT 0,
    requiredskillrank INTEGER NOT NULL    DEFAULT 0,
    minlevel          INTEGER NOT NULL    DEFAULT 0
);
