DROP TABLE IF EXISTS dbc.dbc_itemset;

CREATE TABLE dbc.dbc_itemset
(
    id                integer PRIMARY KEY DEFAULT 0,
    name_lang_enus    text,
    name_lang_engb    text,
    name_lang_kokr    text,
    name_lang_frfr    text,
    name_lang_dede    text,
    name_lang_encn    text,
    name_lang_zhcn    text,
    name_lang_entw    text,
    name_lang_zhtw    text,
    name_lang_eses    text,
    name_lang_esmx    text,
    name_lang_ruru    text,
    name_lang_ptpt    text,
    name_lang_ptbr    text,
    name_lang_itit    text,
    name_lang_unk     text,
    name_lang_mask    bigint  NOT NULL    DEFAULT 0,

    itemid_1          integer NOT NULL    DEFAULT 0,
    itemid_2          integer NOT NULL    DEFAULT 0,
    itemid_3          integer NOT NULL    DEFAULT 0,
    itemid_4          integer NOT NULL    DEFAULT 0,
    itemid_5          integer NOT NULL    DEFAULT 0,
    itemid_6          integer NOT NULL    DEFAULT 0,
    itemid_7          integer NOT NULL    DEFAULT 0,
    itemid_8          integer NOT NULL    DEFAULT 0,
    itemid_9          integer NOT NULL    DEFAULT 0,
    itemid_10         integer NOT NULL    DEFAULT 0,
    itemid_11         integer NOT NULL    DEFAULT 0,
    itemid_12         integer NOT NULL    DEFAULT 0,
    itemid_13         integer NOT NULL    DEFAULT 0,
    itemid_14         integer NOT NULL    DEFAULT 0,
    itemid_15         integer NOT NULL    DEFAULT 0,
    itemid_16         integer NOT NULL    DEFAULT 0,
    itemid_17         integer NOT NULL    DEFAULT 0,

    setspellid_1      integer NOT NULL    DEFAULT 0,
    setspellid_2      integer NOT NULL    DEFAULT 0,
    setspellid_3      integer NOT NULL    DEFAULT 0,
    setspellid_4      integer NOT NULL    DEFAULT 0,
    setspellid_5      integer NOT NULL    DEFAULT 0,
    setspellid_6      integer NOT NULL    DEFAULT 0,
    setspellid_7      integer NOT NULL    DEFAULT 0,
    setspellid_8      integer NOT NULL    DEFAULT 0,

    setthreshold_1    integer NOT NULL    DEFAULT 0,
    setthreshold_2    integer NOT NULL    DEFAULT 0,
    setthreshold_3    integer NOT NULL    DEFAULT 0,
    setthreshold_4    integer NOT NULL    DEFAULT 0,
    setthreshold_5    integer NOT NULL    DEFAULT 0,
    setthreshold_6    integer NOT NULL    DEFAULT 0,
    setthreshold_7    integer NOT NULL    DEFAULT 0,
    setthreshold_8    integer NOT NULL    DEFAULT 0,

    requiredskill     integer NOT NULL    DEFAULT 0,
    requiredskillrank integer NOT NULL    DEFAULT 0
);
