DROP TABLE IF EXISTS dbc.dbc_faction;

CREATE TABLE dbc.dbc_faction
(
    id                    integer NOT NULL DEFAULT 0 PRIMARY KEY,
    reputationindex       integer NOT NULL DEFAULT 0,
    reputationracemask_1  integer NOT NULL DEFAULT 0,
    reputationracemask_2  integer NOT NULL DEFAULT 0,
    reputationracemask_3  integer NOT NULL DEFAULT 0,
    reputationracemask_4  integer NOT NULL DEFAULT 0,
    reputationclassmask_1 integer NOT NULL DEFAULT 0,
    reputationclassmask_2 integer NOT NULL DEFAULT 0,
    reputationclassmask_3 integer NOT NULL DEFAULT 0,
    reputationclassmask_4 integer NOT NULL DEFAULT 0,
    reputationbase_1      integer NOT NULL DEFAULT 0,
    reputationbase_2      integer NOT NULL DEFAULT 0,
    reputationbase_3      integer NOT NULL DEFAULT 0,
    reputationbase_4      integer NOT NULL DEFAULT 0,
    reputationflags_1     integer NOT NULL DEFAULT 0,
    reputationflags_2     integer NOT NULL DEFAULT 0,
    reputationflags_3     integer NOT NULL DEFAULT 0,
    reputationflags_4     integer NOT NULL DEFAULT 0,
    parentfactionid       integer NOT NULL DEFAULT 0,
    parentfactionmod_1    float4  NOT NULL DEFAULT 0,
    parentfactionmod_2    float4  NOT NULL DEFAULT 0,
    parentfactioncap_1    integer NOT NULL DEFAULT 0,
    parentfactioncap_2    integer NOT NULL DEFAULT 0,

    name_lang_enus        text,
    name_lang_engb        text,
    name_lang_kokr        text,
    name_lang_frfr        text,
    name_lang_dede        text,
    name_lang_encn        text,
    name_lang_zhcn        text,
    name_lang_entw        text,
    name_lang_zhtw        text,
    name_lang_eses        text,
    name_lang_esmx        text,
    name_lang_ruru        text,
    name_lang_ptpt        text,
    name_lang_ptbr        text,
    name_lang_itit        text,
    name_lang_unk         text,
    name_lang_mask        bigint  NOT NULL DEFAULT 0,

    description_lang_enus text,
    description_lang_engb text,
    description_lang_kokr text,
    description_lang_frfr text,
    description_lang_dede text,
    description_lang_encn text,
    description_lang_zhcn text,
    description_lang_entw text,
    description_lang_zhtw text,
    description_lang_eses text,
    description_lang_esmx text,
    description_lang_ruru text,
    description_lang_ptpt text,
    description_lang_ptbr text,
    description_lang_itit text,
    description_lang_unk  text,
    description_lang_mask bigint  NOT NULL DEFAULT 0
);
