DROP TABLE IF EXISTS dbc.dbc_spellshapeshiftform;

CREATE TABLE dbc.dbc_spellshapeshiftform
(
    id                  INTEGER PRIMARY KEY DEFAULT 0,
    bonusactionbar      INTEGER NOT NULL DEFAULT 0,
    name_lang_enus      TEXT,
    name_lang_engb      TEXT,
    name_lang_kokr      TEXT,
    name_lang_frfr      TEXT,
    name_lang_dede      TEXT,
    name_lang_encn      TEXT,
    name_lang_zhcn      TEXT,
    name_lang_entw      TEXT,
    name_lang_zhtw      TEXT,
    name_lang_eses      TEXT,
    name_lang_esmx      TEXT,
    name_lang_ruru      TEXT,
    name_lang_ptpt      TEXT,
    name_lang_ptbr      TEXT,
    name_lang_itit      TEXT,
    name_lang_unk       TEXT,
    name_lang_mask      BIGINT NOT NULL DEFAULT 0,
    flags               INTEGER NOT NULL DEFAULT 0,
    creaturetype        INTEGER NOT NULL DEFAULT 0,
    attackiconid        INTEGER NOT NULL DEFAULT 0,
    combatroundtime     INTEGER NOT NULL DEFAULT 0,
    creaturedisplayid_1 INTEGER NOT NULL DEFAULT 0,
    creaturedisplayid_2 INTEGER NOT NULL DEFAULT 0,
    creaturedisplayid_3 INTEGER NOT NULL DEFAULT 0,
    creaturedisplayid_4 INTEGER NOT NULL DEFAULT 0,
    presetspellid_1     INTEGER NOT NULL DEFAULT 0,
    presetspellid_2     INTEGER NOT NULL DEFAULT 0,
    presetspellid_3     INTEGER NOT NULL DEFAULT 0,
    presetspellid_4     INTEGER NOT NULL DEFAULT 0,
    presetspellid_5     INTEGER NOT NULL DEFAULT 0,
    presetspellid_6     INTEGER NOT NULL DEFAULT 0,
    presetspellid_7     INTEGER NOT NULL DEFAULT 0,
    presetspellid_8     INTEGER NOT NULL DEFAULT 0
);
